### ISSUE TITLE
Relayout causes scroll position to jump to center

### ISSUE THREAD

**Issue by cavey79** [MikeOrtiz/TouchImageView#100]
I have the TouchImageView as part of a FrameLayout that gets a call to requestLayout (because one of the other children received requestLayout).

This causes another measure pass and the image is then centered (zoom is retained though).

If it helps, here is the relevant part of the layout code:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="horizontal"
              android:layout_width="fill_parent"
              android:layout_height="fill_parent"
        >

    <FrameLayout
            android:layout_width="0dp"
            android:layout_height="fill_parent"
            android:layout_weight="1"
            android:layout_margin="2dp"
            >

        <com.ortiz.touch.TouchImageView
                android:id="@+id/pixel_view"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                />

        <ImageView
                android:id="@+id/pixel_preview_view"
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:background="#ffffffff"
                android:scaleType="fitCenter"
                android:layout_margin="0dp"
                android:padding="0dp"
                android:layout_gravity="bottom|right"
                />

    </FrameLayout>
</LinearLayout>
```

I'm calling requestLayout on the pixel_preview_view which causes the described issue.

**Comment by JVillella** [comment]
To build upon what Ray mentioned, to keep `savePreviousImageValues()` private (which it should - it should know when to save its values, not have an outside class deal with its internals) I have made a small change to the `fitImageToView()` method. When the system goes through a layout pass, on `onMeasure()` gets called. In turn `onMeasure()` calls `fitImageToView()`.

Inside `fitImageToView()` you will see something like this (about half way down the method):

    ...
    // These values should never be 0 or we will set viewWidth and viewHeight
    // to NaN in translateMatrixAfterRotate. To avoid this, call savePreviousImageValues
    // to set them equal to the current values.
    //
    if (prevMatchViewWidth == 0 || prevMatchViewHeight == 0) {
        savePreviousImageValues();
    }
    ...

Just remove that if condition and you'll be okay.

    ...
    // These values should never be 0 or we will set viewWidth and viewHeight
    // to NaN in translateMatrixAfterRotate. To avoid this, call savePreviousImageValues
    // to set them equal to the current values.
    //
    savePreviousImageValues();
    ...

If anyone sees an issue with this please let me know. My fork of this repo includes this fix (and a bunch of other improvements). https://github.com/JVillella/TouchImageView

**Comment by bartek-wesolowski** [comment]
@JVillella If you remove the if statement, TouchImageView doesn't handle orientation changes correctly anymore.
