### ISSUE TITLE
TouchImageView Padding on ViewPager

### ISSUE THREAD

**Issue by fedlerner** [MikeOrtiz/TouchImageView#102]
When you add padding to your TouchImageView (at least on the ViewPager Activity), the padding doesn't work as it should. I added padding on the left and right. The padding on the left works, but the padding on the right doesn't (and also, the image gets "cropped").

To reproduce this problem, add the img.setPadding(...) to ViewPagerExampleActivity.java, for example :
@Override
        public View instantiateItem(ViewGroup container, int position) {
            TouchImageView img = new TouchImageView(container.getContext());
            img.setPadding(20, 20, 20, 20);
            img.setImageResource(images[position]);
            container.addView(img, LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
            return img;
        }

This works with ImageView, but it doesn't work with TouchImageView

**Comment by zdd** [comment]
I have the same issue, do you find a solution?

**Comment by sipersoft** [comment]
Ran into this problem today. In case anyone else has this issue, the solution I've come up with is the following:

Within `setZoom`

        scaleImage(scale, (viewWidth - getPaddingLeft() - getPaddingRight()) / 2, (viewHeight - getPaddingTop() - getPaddingBottom()) / 2, true);
        matrix.getValues(m);
        m[Matrix.MTRANS_X] = -((focusX * getImageWidth()) - ((viewWidth - getPaddingLeft() - getPaddingRight()) * 0.5f));
        m[Matrix.MTRANS_Y] = -((focusY * getImageHeight()) - ((viewHeight - getPaddingTop() - getPaddingBottom()) * 0.5f));

Within `getScrollPosition`

        PointF point = transformCoordTouchToBitmap((viewWidth - getPaddingLeft() - getPaddingRight()) / 2, (viewHeight - getPaddingTop() - getPaddingBottom()) / 2, true);

Within `fixTrans`

        float fixTransX = getFixTrans(transX, (viewWidth - getPaddingLeft() - getPaddingRight()), getImageWidth());
        float fixTransY = getFixTrans(transY, (viewHeight - getPaddingTop() - getPaddingBottom()), getImageHeight());

Within `fixScaleTrans`

        if (getImageWidth() < (viewWidth - getPaddingLeft() - getPaddingRight())) {
            m[Matrix.MTRANS_X] = ((viewWidth - getPaddingLeft() - getPaddingRight()) - getImageWidth()) / 2;
        }

        if (getImageHeight() < (viewHeight - getPaddingTop() - getPaddingBottom())) {
            m[Matrix.MTRANS_Y] = ((viewHeight - getPaddingTop() - getPaddingBottom()) - getImageHeight()) / 2;
        }

Finally, all within `fitImageToView`

        float scaleX = (float) (viewWidth - getPaddingRight() - getPaddingLeft()) / drawableWidth;
        float scaleY = (float) (viewHeight - getPaddingBottom() - getPaddingTop()) / drawableHeight;

... and

        float redundantXSpace = (viewWidth - getPaddingRight() - getPaddingLeft()) - (scaleX * drawableWidth);
        float redundantYSpace = (viewHeight - getPaddingBottom() - getPaddingTop()) - (scaleY * drawableHeight);
        matchViewWidth = (viewWidth - getPaddingRight() - getPaddingLeft()) - redundantXSpace;
        matchViewHeight = (viewHeight - getPaddingBottom() - getPaddingTop()) - redundantYSpace;

... and 

            translateMatrixAfterRotate(Matrix.MTRANS_X, transX, prevActualWidth, actualWidth, prevViewWidth, (viewWidth - getPaddingLeft() - getPaddingRight()), drawableWidth);

... and

            translateMatrixAfterRotate(Matrix.MTRANS_Y, transY, prevActualHeight, actualHeight, prevViewHeight, (viewHeight - getPaddingTop() - getPaddingBottom()), drawableHeight);

It's a bit of a hack job, but seems to get the right results for me. Only tested in portrait view, sorry if it doesn't work otherwise. Setting ALL `viewWidth` and `viewHeight` to have the padding removed will give undesirable results. It is just this combination that gets proper left/right and top/bottom padding.

When I set the padding, it is as follows:

    TouchImageView tv = new TouchImageView(getActivity());
    tv.setPadding(10, 50, 10, 20);
    tv.setImageResource(...);

i.e. setting the padding before anything else. This likely doesn't have an effect on the padding, but is how I went about it.

**Comment by hannesa2** [comment]
It's 4 years old, so it seems to be irrelevant. If it's still an issue, please reopen it

**Comment by hannesa2** [comment]
It's probably solved with #655
