### ISSUE TITLE
How to save the edited image?

### ISSUE THREAD

**Issue by zak84** [MikeOrtiz/TouchImageView#105]
Hello, i want to use your class, to let the user play with an image.
But how can i save the edited image in a file?
Basically... how can i edit the original image and put it in a new file?
I think a save() function in your class would be helpful and a good integration/completition of your work.

**Comment by kotya341** [comment]
Hi Zak I have the same question.Can you please explain how you resolved this problem?

**Comment by zak84** [comment]
For sure!
Hope you can understand what i'm doing, because is a piece of an app:

TouchImageView prova=(TouchImageView)findViewById(100+y);
RectF rect= prova.getZoomedRect();
bmp = BitmapFactory.decodeFile(selectedItems.get(y));
int larghezza=bmp.getWidth();
int altezza=bmp.getHeight();
Float x1=larghezza*rect.left;
Float x2=(larghezza*rect.right)-x1;
Float y1=altezza*rect.top;
Float y2=(altezza*rect.bottom)-y1;
bmp=Bitmap.createBitmap(bmp, Math.round(x1), Math.round(y1), Math.round(x2), Math.round(y2));

**Comment by kotya341** [comment]
To be honest I don't understand what is larghezzarect and altezzarect.

**Comment by zak84** [comment]
Well, it's github that stripped out my *
altezzarect is altezza * rect
larghezzarect is larghezza * rect

**Comment by kotya341** [comment]
Anyway after  creating new rectagle my x coordinate become negative
https://gist.github.com/kotya341/ef51ff010f0a411036ba
And this means that I do something wrong :)

**Comment by zak84** [comment]
Don't know what. Maybe it's something else.
Because i've created an app which parse more than 20 images at the same time, and have a lot of users.
So the code works.

**Comment by kotya341** [comment]
I am sure that your code working correct that's why I am looking for piece of advice from you. Can you please provide more detailed example ?

**Comment by MikeOrtiz** [comment]
@kotya341 Check out getZoomedImage() and getZoomedImageFromSource() in this commit: https://github.com/MikeOrtiz/TouchImageView/commit/d0b66f7e7ed1fb5093784f59a3ace554151274c1. They were previously available in the public API but have since been removed.
