### ISSUE TITLE
Get touched coordinates on Image

### ISSUE THREAD

**Issue by maxmousee** [MikeOrtiz/TouchImageView#11]
Get where the user is touching in the image (x,y) with the image reference in any zoom?
Is it possible?

**Comment by androidovshchik** [comment]
This worked for me
```
imageView.setOnTouchListener { _, event ->
    if (event.action != MotionEvent.ACTION_DOWN) {
        return@setOnTouchListener false
    }
    val transformCoordTouchToBitmap = main.javaClass.getDeclaredMethod("transformCoordTouchToBitmap",
        Float::class.java, Float::class.java, Boolean::class.java)
    transformCoordTouchToBitmap.isAccessible = true
    val bitmapPoint = transformCoordTouchToBitmap.invoke(main, event.x, event.y, true) as PointF
    return@setOnTouchListener false
}
```

**Comment by werohit** [comment]
> This worked for me
> 
> ```
> imageView.setOnTouchListener { _, event ->
>     if (event.action != MotionEvent.ACTION_DOWN) {
>         return@setOnTouchListener false
>     }
>     val transformCoordTouchToBitmap = main.javaClass.getDeclaredMethod("transformCoordTouchToBitmap",
>         Float::class.java, Float::class.java, Boolean::class.java)
>     transformCoordTouchToBitmap.isAccessible = true
>     val bitmapPoint = transformCoordTouchToBitmap.invoke(imageView, event.x, event.y, true) as PointF
>     return@setOnTouchListener false
> }
> ```
> 
> `bitmapPoint` contains pixel coordinates of bitmap

Worked for me as well, Thanks a ton bro

**Comment by hannesa2** [comment]
It it this, what you want ? #357 

```
   binding.imageSingle.setOnTouchCoordinatesListener(object: OnTouchCoordinatesListener {
            override fun onTouchCoordinate(view: View, event: MotionEvent, bitmapPoint: PointF) {
                binding.touchCoordinates.text = "touch coordinates x=${bitmapPoint.x} y=${bitmapPoint.y}"
            }
        })

```
https://github.com/MikeOrtiz/TouchImageView/pull/357/files#diff-32a3a06a7b8d99f785c9fa83b959c286cb1c9a65da8f3af3d2892c3820973068R46-R50

**Comment by hannesa2** [comment]
@androidovshchik before you work with reflections, I recommend to make a pull request

**Comment by hannesa2** [comment]
A new release https://github.com/MikeOrtiz/TouchImageView/releases/tag/refs%2Ftags%2F3.1.0
