### ISSUE TITLE
Pager Adapter - private static int[] images

### ISSUE THREAD

**Issue by dtnewsan** [MikeOrtiz/TouchImageView#110]
Hi everyone!

I'm new in Github and have just found this amazing project, I'm very happy with it.

I'm having a little issue, tough.

I'm using images by id like: m1.jpg , m2.jpg, m3.jpg, etc.

The thing is that the pager has the images variable that only allows to add images manually.

What modification should I use to load an array automatically visible for all the class TouchImageAdapter?

Thanks in advance!

**Comment by hannesa2** [comment]
It's almost 5 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
