### ISSUE TITLE
The TouchImageView's onDraw method runs before setImageBitmap,so the image did not show

### ISSUE THREAD

**Issue by cuixbo** [MikeOrtiz/TouchImageView#112]
In your demo it runs ok,but in my application the image doesn't show.
while i add "imageRenderedAtLeastOnce = false;" in the method setImageBitmap,it runs ok in my application.

```
    @Override
    public void setImageBitmap(Bitmap bm) {
        imageRenderedAtLeastOnce = false;
        super.setImageBitmap(bm);
        savePreviousImageValues();
        fitImageToView();
    }
```

i debuged my application ,i found that the method "ondraw" runs before the method "setImageBitmap",so this filed "imageRenderedAtLeastOnce"  may be influenced.
i do not know why?

**Comment by Logko** [comment]
I was suffering same issue, thanks for your solution @cuixbo

**Comment by edkimmel** [comment]
This solution worked for me too. If you use this class to display images loaded from the network, and you experience any kind of 'image not showing' bug, try this solution out.

**Comment by amarilindra** [comment]
I have answered a possible solution [here](https://github.com/MikeOrtiz/TouchImageView/issues/135#issuecomment-259341153)

**Comment by saurabhojha075** [comment]
thanks bro u save my day...

**Comment by SalmaSayed** [comment]
in what file should I put this ? 
I implement that with kotlin 

```
@Override
    public void setImageBitmap(Bitmap bm) {
        imageRenderedAtLeastOnce = false;
        super.setImageBitmap(bm);
        savePreviousImageValues();
        fitImageToView();
    }
```
