### ISSUE TITLE
regarding problem in api level 

### ISSUE THREAD

**Issue by engr-erum** [MikeOrtiz/TouchImageView#114]
@TargetApi(Build.VERSION_CODES.JELLY_BEAN)
    private void compatPostOnAnimation(Runnable runnable) {
        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
            postOnAnimation(runnable);

```
    } else {
        postDelayed(runnable, 1000 / 60);
    }
}
```

i m using api level 4.0  and its throwing error on @TargetApi(Build.VERSION_CODES.JELLY_BEAN)   that " JELLY_BEAN cannot be resolved or is not a field"

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
