### ISSUE TITLE
TouchImage View Doesnt align the Image center in Small resolution devices

### ISSUE THREAD

**Issue by subrhmanyam** [MikeOrtiz/TouchImageView#115]
![screenshot_2015-01-22-11-36-24 1](https://cloud.githubusercontent.com/assets/10473130/5852127/bb966c4a-a237-11e4-91a7-de57853f4844.png)

The TouchImageView layouts the Image from Top left corner & on double tap the image disappers  some Devices the Image is not at all visible. Problem with Setting the Xy position

Note: Doesnt Occur on all devices

**Comment by hannesa2** [comment]
It's almost 4 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
