### ISSUE TITLE
free move the image

### ISSUE THREAD

**Issue by smoi** [MikeOrtiz/TouchImageView#121]
I want to be able to move the image even if I have a big image view ie 1000x500px and I zoom out the image to be ie 200x100 I want to be able to move the image wherever in the big ImageView, is this possible? Currently if I do that the image stays in the middle of the ImageView and it's not possible to move it

Thanks

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
