### ISSUE TITLE
Zoom out/in animation is not smooth.

### ISSUE THREAD

**Issue by zdd** [MikeOrtiz/TouchImageView#122]
When I double tap to zoom, There is a little shake at the end of zoom out/in, not very smooth.

**Comment by biguas** [comment]
It is also happening when I hide actionbar, any help from someone??

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR

**Comment by DanteAndroid** [comment]
I met this as well. And I tried https://github.com/chrisbanes/PhotoView, same issue.
