### ISSUE TITLE
Padding only works for left and top side, not work for right and bottom side.

### ISSUE THREAD

**Issue by zdd** [MikeOrtiz/TouchImageView#123]
I have a image displayed in an Activity and I want to setting padding=10dp for each side. the xml layout looks like below.

<com.jiyuzhai.touchimageview.TouchImageView
        android:id="@+id/full_image_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_above="@+id/pageInfo"
        android:padding="10dp"
        android:layout_centerInParent="true"
        android:scaleType="centerCrop"
        android:background="@drawable/whitecolor"/>

But, the padding only display at the left and top side, there is no padding at the right and bottom side.

The padding works well with native ImageView. any idea?

**Comment by hannesa2** [comment]
It's 4 years old, so it seems to be irrelevant. If it's still an issue, please reopen it

**Comment by hannesa2** [comment]
It's probably solved with #655
