### ISSUE TITLE
Images don't displayed

### ISSUE THREAD

**Issue by Katkov** [MikeOrtiz/TouchImageView#125]
I found out on Samsung Galaxy S4 using TouchImageView with VerticalViewPager that images are not displayed very often. It turned out that m[Matrix.MSCALE_X] = NaN and m[Matrix.MSCALE_Y] = NaN. 
In my project, 
I fixed it changing in the method: 
translateMatrixAfterRotate(int axis, float trans, float prevImageSize, float imageSize, int prevViewSize, int viewSize, int drawableSize)
the next line: 
            percentage = (Math.abs(trans) + (0.5f \* prevViewSize)) / prevImageSize; 
to the next snippet: 
            float percentage;
            if(prevImageSize != 0) {
                percentage = (Math.abs(trans) + (0.5f \* prevViewSize)) / prevImageSize;
            } else {
                percentage = 0;
            }

**Comment by TheNetStriker** [comment]
I've also had this problem, thanks for your fix. Please implement this fix in the project.

**Comment by Katkov** [comment]
I forked it on my repository. You can take it by https://github.com/Katkov/TouchImageView.git.

**Comment by jrvansuita** [comment]
Thanks bro.

**Comment by rahulkalpsts107** [comment]
thankyou katkov. The issue i saw was present irrespective of rotate but your above fix has helped.

**Comment by iori57** [comment]
I spent hours looking for the issue. I have no idea why it happens on one of my activity but not the other, despite the layout looking almost the same.
After trying your fix without much hope, it works wonderfully. Thanks!

**Comment by Niroj08** [comment]
Thank you  @Katkov  for the tweak

**Comment by GeorgePractics23** [comment]
You kill it @Katkov!! Thank you for this!

**Comment by ShashKiran** [comment]
Thank you so much @Katkov

**Comment by deepakcipl** [comment]
Same problem I was facing. I have solved the problem by setting zoom 0.99f as follows:-
imageView.setZoom(0.99f);

where imageView is reference of TouchImageView. I was facing this problem in ImageLoader, so I just put the above line in onLoadingComplete method. You can also put the same line before loading the image url  to glide or ImageLoader but better to put it after loading complete. Enjoy :)

**Comment by hannesa2** [comment]
It seems to be irrelevant now. If it's still an issue, please reopen it
