### ISSUE TITLE
Click event not working on TouchImageView is not working

### ISSUE THREAD

**Issue by ShreyashPromact** [MikeOrtiz/TouchImageView#127]
Please let me know how to have click event on TouchImageView? I have try a lot but i guess you have implemented Gesture listener on TouchImageView that's why i am not getting Click event on the ImageView. Please update it to have click event also or let me know how i can do that.

FYI, double Tap and gesture works fine. Only issue with click on the ImageView.

Thanks.

**Comment by black-snow** [comment]
Need to set GestureListener on a ViewPager that holds a TouchImageView but I'm not getting any events through. I need onSingleTapConfirmed() - clearely TouchImageView needs to process swipes and double taps. Any guess why I'm not getting any touch event / gesture?

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
