### ISSUE TITLE
wrong isZoomed() value

### ISSUE THREAD

**Issue by Radiokot** [MikeOrtiz/TouchImageView#131]
Due to the fact that normalizedScale is a float value, comparing it with the integral 1 sometimes gives the wrong result. So right code for isZoomed() must be 
return Math.abs(normalizedScale - 1) >= 0.1;

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
