### ISSUE TITLE
Little problem when creating the control with no image / adding an image later.

### ISSUE THREAD

**Issue by IanEH** [MikeOrtiz/TouchImageView#133]
To do with initial sizing I think will look at it when I get a min but got round it by adding a tiny dummy image when creating the control. Used it in my little play forms app. https://github.com/IanEH/YASFA1 hope that's OK and thanks works well.

**Comment by ithillel-YuriiSolopov** [comment]
This chages helped for me:
@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        Drawable drawable = getDrawable();
        if (drawable == null || drawable.getIntrinsicWidth() == 0 || drawable.getIntrinsicHeight() == 0) {
        	**super.onMeasure(widthMeasureSpec,heightMeasureSpec);**
            //setMeasuredDimension(0, 0);
        	return;
        }

**Comment by iori57** [comment]
Thanks @ithillel-YuriiSolopov! I was wondering why it behaves differently compare to normal ImageView, your comment helped me to figure this out :)

**Comment by hannesa2** [comment]
It seems to be irrelevant. If it's still an issue, please reopen it
