### ISSUE TITLE
Have problems when a SeekBar is running with a handler.

### ISSUE THREAD

**Issue by AngelOfDestiny** [MikeOrtiz/TouchImageView#134]
Hi, Firstly I want to say that TouchImageView Class worked fine for me, But I have a problem. When a SeekBar is running with a handler help, I want to zoom TouchImageView, and it works, but I cant move the Image, only if the SeekBar is not running, I can zoom TouchImageView and move wherever I want.

Can you Help me? this is the code of the handler that I have:

private Handle handler = new Handler();
MediaPlayer player = new MediaPlayer();
...

private Runnable timer = new Runnable() {
            public void run() {

```
        seekbar.setProgress(player.getCurrentPosition());
            handler.postDelayed(this, 100);

    }
```

};

Obviously , player is not null and is playing.

**Comment by hannesa2** [comment]
It's almost 4 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
