### ISSUE TITLE
Using TouchImageView with Glide library

### ISSUE THREAD

**Issue by niteshkhatri** [MikeOrtiz/TouchImageView#135]
Hi, when I display the image using Glide library, I can't see the Image. However is I use setImageBitmap() method, the image is perfectly displayedwith all zoom capabilities.

How can I use TouchImageView with Glide library?

**Comment by Ralphilius** [comment]
You can try this:

        Glide.with(context).load(url).asBitmap().into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                yourImageView.setImageBitmap(resource);
            }
        });

I can show the images with ViewPager and Glide successfully.

**Comment by Bluesir9** [comment]
I have an older version of the project which has zoom and pan but without double tap. That loads the images with glide perfectly. 
But the TouchImageView doesn't load anything when using Glide. I even tried the suggestion made in #112 but that didn't work either.
Do note that the way i am loading images using Glide is as below:

Glide.with(getActivity()).load(imageUrl).into(imageView);

And that is working perfectly everywhere else except here.

**Comment by eshaanb** [comment]
What @Ralphilius said works - but what if I want to add a .thumbnail() as well using glide.load() inside of that?

**Comment by lukesleeman** [comment]
I have been having the same issue.  It seems to occur only when glide was loading the image over the network, not when it was returned from the cache.  I found that the fix mentioned in #112 of adding:
      imageRenderedAtLeastOnce = false;
into the setImageBitmap method fixed my problem

**Comment by aimanbaharum** [comment]
@Ralphilius solution works for me. However, the image only appear after I pinch the screen a little bit. Someone tell me what's the issue here? How can I debug this?

**Comment by ThatKawaiiGuy** [comment]
Is there a way to get this working with GIFs?

**Comment by amarilindra** [comment]
I know I'm too late for the party but I did some trail/error on this issue and I found a solution. 

Instead of loading image as path, i tried to load as File and it worked. 

```
Glide.with(mContext)
                .load(new File(imagePath))
                .placeholder(R.drawable.default_placeholder)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .skipMemoryCache(false)
                .into(imageview_featured_image);
```

**Comment by oliverbob** [comment]
@Ralphilius' solution works on low resolution images. I wonder if there is a way to handle something like 7000 x 3000 size.

**Comment by DenisShov** [comment]
Thanks to @lukesleeman, that pointed to the solution! I finally fixed it. Image showed only after the first loading. And now it works.

**Comment by waqarul** [comment]
I've resolved issue as suggested by @aimanbaharum 

setting the initial zoom by 1f

**Comment by rakeshvihan** [comment]
@Ralphilius What is the solution to load both bitmap and gif?

**Comment by Laplateau** [comment]
Hi there,

Once again, TouchImageView is having some compatibility issues with Glide. The newest stable release of Glide (v4.0.0-RC0) does not seem to properly feed images into TouchImageView irrespective of which of the solutions mentioned on this page I try. @Ralphilius 's solution does work, but loading the image as a bitmap is too slow for the fairly large images that I need to load into TouchImageView. Would anyone have any suggestions for techniques I could try to make this work? Thanks so much!

**Comment by pizzetto** [comment]
I have been able to load an Animated Gif into TouchImageView, here is my solution:

```
 public static void loadGif(String url, final TouchImageView view) {
        L.d("GlideGifTouch url " + url);
        if (isValidUrl(url)) {
            SimpleTarget<GifDrawable> target = new SimpleTarget<GifDrawable>() {
                @Override
                public void onResourceReady(GifDrawable resource, Transition<? super GifDrawable> transition) {
                    resource.start();
                    view.setImageDrawable(resource);
                }
            };
            GlideApp.with(view.getContext()).asGif().load(url).into(target);
        }
    }
```

Hope this helps

**Comment by gelbertgel** [comment]
and my solution is   `  .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)`

            ```
  glideRequests.load(path)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .dontTransform()
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .transition(withCrossFade())
                .into(imageView);
```

**Comment by Testuser36** [comment]
@ralphilius  I am using Glide.  Below is my code :: 
  Glide.with(context).asBitmap().load(images.get(position)).into(new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap resource, Transition<? super Bitmap> transition) {
                    imageView.setImageBitmap(resource);
                }
            });

My 1st image is not getting load. After I scroll 2-3 times to other images in ViewPager only then the image is getting load.

**Comment by ShivamPokhriyal** [comment]
I had the same issue while loading image from url into TouchImageView using Glide. It would show a black screen. 
I found a fix which works like this. Pass width and height in Glide override method and after setting bitmap call setzoom of TouchImageView with value 1.

Here is the complete code:

Glide.with(#context)
                        .asBitmap()
                        .load(#url)
                        .apply(new RequestOptions().override(1600, 1600)) //This is important 
                        .into(new BitmapImageViewTarget(#imageview) {
                            @Override
                            public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                                super.onResourceReady(resource, transition);
                                #imageview.setImageBitmap(resource);
                                #imageview.setZoom(1);
                            }
                        });

**Comment by ShivamPokhriyal** [comment]
I had the same issue while loading image from url into TouchImageView using Glide. It would show a black screen. 
I found a fix which works like this. Pass width and height in Glide override method and after setting bitmap call setzoom of TouchImageView with value 1.

Here is the complete code:

Glide.with(#context)
                        .asBitmap()
                        .load(#url)
                        .apply(new RequestOptions().override(1600, 1600)) //This is important 
                        .into(new BitmapImageViewTarget(#imageview) {
                            @Override
                            public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                                super.onResourceReady(resource, transition);
                                #imageview.setImageBitmap(resource);
                                #imageview.setZoom(1); //This is important
                            }
                        });

**Comment by kalyandechiraju** [comment]
> You can try this:
> 
> ```
>     Glide.with(context).load(url).asBitmap().into(new SimpleTarget<Bitmap>() {
>         @Override
>         public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
>             yourImageView.setImageBitmap(resource);
>         }
>     });
> ```
> I can show the images with ViewPager and Glide successfully.

This worked perfectly

```
Glide.with(context).asBitmap().load(url).into(new SimpleTarget<Bitmap>() {
        @Override
        public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
            // Hide progress bar
            yourImageView.setImageBitmap(resource);
        }
    });
```

**Comment by hannesa2** [comment]
It's 5 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
