### ISSUE TITLE
Disable drag and fling

### ISSUE THREAD

**Issue by dekaDwi** [MikeOrtiz/TouchImageView#138]
Hi Mike,
how to disable drag and fling?

**Comment by hannesa2** [comment]
It's 4 years old, so it seems to be irrelevant. If it's still an issue, please reopen it

**Comment by tianye2856** [comment]
Please open this problem.
How to disable flying feature?

**Comment by hannesa2** [comment]
Please see https://github.com/MikeOrtiz/TouchImageView/issues/395#issuecomment-916060322
