### ISSUE TITLE
How To Start TouchImageView With Initial Pan & Zoom

### ISSUE THREAD

**Issue by dmanpearl** [MikeOrtiz/TouchImageView#14]
I am using TouchImageView to display images that I had previously been displaying with ImageView. Thank you very much for this great tool!!

I have to initialize the TouchImageView with the pan and zoom values from a previous use, or a minimum and/or default zoom value. I currently do this by injecting gestures with a timer which is certainly not optimal. Can you tell me how to initialize a new TouchImageView with pan and zoom values from a previous TouchImageView.

Thanks!
- David

**Comment by Groovee60** [comment]
With the current version from GitHub, I'm finding that the center point is not properly calculated if setZoom(2.0f, 0.5f, 0.5f)  (for example) is called during onCreate(). If the same call is made after the view is up and visible, it's fine. Other than this small issue, the view implemenation seems terrific.
