### ISSUE TITLE
'canScrollVertically' is never called within the TouchImageView

### ISSUE THREAD

**Issue by ghost** [MikeOrtiz/TouchImageView#141]
`canScrollVertically` is never called within the TouchImageView - [full description of the issue](http://stackoverflow.com/questions/33789774/android-canscrollvertically-never-called-for-imageview) at StackOverflow.

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
