### ISSUE TITLE
Increase function

### ISSUE THREAD

**Issue by nianzixin** [MikeOrtiz/TouchImageView#142]
You can add the following functions on the basis of the demo, when this picture than the original contract that touch can rotate a picture, when the picture rotation greater than 45 degrees, automatic rotation of 90 degrees, if less than image reduction does not rotate.

**Comment by nianzixin** [comment]
中国知名软件qq就是是这样做的，当我们预览的图片是倒立的，我们可以通过旋转使图片正向显示，满足视觉需求。

**Comment by nianzixin** [comment]
Chinese well-known software QQ is to do so, when we preview the picture is inverted, we can be rotated to make the picture is forward to meet the visual needs.

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
