### ISSUE TITLE
TouchImageView ontouch pan/fling event is not working smoothly

### ISSUE THREAD

**Issue by androidiseverythingforme** [MikeOrtiz/TouchImageView#143]
Hi i am using your custom image view in my code i have adapterView i.e  gridview in which am inflating your image view but problem is that i am not able to smoothly pan/fling the image view 

i think i need to disable touch event of grid view i tried all the things like setfocusable = false setClickable=false and all but still its not working may i know what i need to do so imageView will pan/fling smoothly or any other configuration i need to do for your custom view

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
