### ISSUE TITLE
How to display number of images and current image index like 1/2 using touch imageview

### ISSUE THREAD

**Issue by tech4solitude** [MikeOrtiz/TouchImageView#150]
Hi Michael Ortiz,

First of all great work and thank you, I just wanted to know is there any way to display number of images and current image index at the top of the image view whenever we are showing multiple images in view  pager.

**Comment by AseedUsmani** [comment]
Crude way of doing that is select a number for each image and display that number in a new TextView. In the current context the last digit of image name would do it. I will try to make a push request soon.

And yes, great library!

**Comment by Punith1234** [comment]
It would be great if you are able to do it in the earliest..:)

**Comment by AseedUsmani** [comment]
If I could get a little suggestion @Punith1234 , how do you or any user for that matter would want it? It depends on how are you fetching the images, like I can do for your drawable directory of the project, that would be simple, I can do if you want to fetch images from a folder; the path of the folder can be manually entered etc... Little suggestion would help.
