### ISSUE TITLE
How to put a String ?

### ISSUE THREAD

**Issue by eduardowski** [MikeOrtiz/TouchImageView#151]
Hi Mike! First that all thank you so much for TouchImageView, i have found it very useful.
I was wondering if it is possible to get the name of the image from a database (String) and put that image into the TouchImageView. I have something like this put it doesn´t work:

TouchImageView imagen = (TouchImageView) findViewById(R.id.imgMiHorario);
int resID = getResources().getIdentifier(imageName, "drawable", getPackageName());
imagen.setImageResource(resID);

Hope you can help me.

**Comment by hannesa2** [comment]
It's 3 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
