### ISSUE TITLE
Create AAR and push to Jcenter

### ISSUE THREAD

**Issue by jaredsburrows** [MikeOrtiz/TouchImageView#154]

**Comment by ligi** [comment]
you can now find a version on jitpack: https://jitpack.io/#ligi/touchimageview/2.1

**Comment by jaredsburrows** [comment]
@ligi It's convenient by I rather it just be on `mavenCentral()` or `jcenter()`.

**Comment by ligi** [comment]
why? jitpack has a way better concept and correlation between code and artifact

**Comment by jaredsburrows** [comment]
We need `jcenter` for android. I don't like adding more repositories to the `repositories` block. It adds more iterations when downloading dependencies.

**Comment by giacomodeglinnocenti** [comment]
Yes, it would be nice to have it on `jcenter`

**Comment by ligi** [comment]
I would not object - but really see no real need for this - would not put any effort in this my self ..
PS: on the version I posted on jitpack are also some improvements ( usage of vectordrawables, .. )

**Comment by jaredsburrows** [comment]
@ligi I finally got around to trying your jitpack version. I am using glide to load an image into the imageview it seems not to work unless I pan the view, then the image appears. Have you experienced anything like this?

**Comment by ligi** [comment]
No - I do not see this issue - but I am also not using glide

**Comment by jaredsburrows** [comment]
Since this is outdated and not kept up, I am now using https://github.com/chrisbanes/PhotoView.

**Comment by hannesa2** [comment]
You could use `implementation 'com.github.MikeOrtiz:TouchImageView:2.1.1'` and if you are interested in jcenter, please make a PR
