### ISSUE TITLE
it does not work well in scrollview

### ISSUE THREAD

**Issue by ebadahmed** [MikeOrtiz/TouchImageView#157]
thanks alot for writing this class,
i have an issue while using scrollview in which i have applied this class, when we put this thing in scroll view and when we zoom in image it expand but we cannot see the whole image 
i will be very thankful to you if you look into this matter 
P.S: sorry for my bad english

**Comment by erginduran** [comment]
Ssame issue here.Hopefully you fix this asap

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
