### ISSUE TITLE
getCurrentZoom() returns 1 always when image is high resolution

### ISSUE THREAD

**Issue by nadinekhatib** [MikeOrtiz/TouchImageView#163]
I was trying to get current zoom level,
i have 1080x1080 image and 3000x3000 px images.
I am using OnTouchImageViewListener to get current zoom whenever user touches the image
with 1080x1080 px images value is correct

but with larger pictures (e.g. 3000px) zoom is always 1

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
