### ISSUE TITLE
Pinch to zoom breaks in ViewPager

### ISSUE THREAD

**Issue by zedoax** [MikeOrtiz/TouchImageView#165]
When used in the ViewHolder for a ViewPager, the image will shrink to the top left corner ~10% of its original size, and start shaking after a pinching to zoom.  When the pinch ends, it will display the correct size, with the desired zoom.  Double tap to zoom still works flawlessly, however

**Comment by arsalankhan994** [comment]
Same issue

**Comment by arsalankhan994** [comment]
I already fixed it. Btw thanks for your reply

**Comment by hannesa2** [comment]
@arsalankhan994  Please let us know, how you were able to solve it
