### ISSUE TITLE
How to get Current X and Y of attached Bitmap?

### ISSUE THREAD

**Issue by shoebhoney** [MikeOrtiz/TouchImageView#167]
Hi,
How to get Current X and Y of attached Bitmap?

thanks!!!

**Comment by lakmalz** [comment]
did u solve this issue?if u find a solution please tell me.i need to do that after zoom also

**Comment by shoebhoney** [comment]
Yes, i solved the issue by following method inside the `TouchImageView.class `

`public PointF getZoomedRect() {
        if (mScaleType == ScaleType.FIT_XY) {
            throw new UnsupportedOperationException("getZoomedRect() not supported with FIT_XY");
        }
        PointF topLeft = transformCoordTouchToBitmap(0, 0, true);
        PointF bottomRight = transformCoordTouchToBitmap(viewWidth, viewHeight, true);

        float w = getDrawable().getIntrinsicWidth();
        float h = getDrawable().getIntrinsicHeight();

        Logger.logsError(TAG,"topLeft : " + topLeft.x + " : " + topLeft.y);
        Logger.logsError(TAG,"bottomRight : " + bottomRight.x + " : " + bottomRight.y);
      
        return  topLeft;
    }`

**Comment by lakmalz** [comment]
i need get user touched image x and y .if it is zoomed or not zoom.but i could not get that values.that is my issue brother.

**Comment by lakmalz** [comment]
Hey thank you very much Shoebhoney. I solved that problem by using transformCoordTouchToBitmap method in TouchImageView.class.
