### ISSUE TITLE
reset zoomed image after moving to other image.

### ISSUE THREAD

**Issue by parthvora25** [MikeOrtiz/TouchImageView#169]
when i zoom in image and then move to other two images, and then come back to this zoomed image. It stays zoomed in + other resetted image overlaps over it. Making two images in a single page.

Action Cancel is fine but dont want to use it. Instead use it after the second image has been loaded.
Help please!!

**Comment by Neetras** [comment]
Hello @parthvora25 
Try this solution of mine if you want the image to zoom out after a new page is selected. addOnPageChangeListener() is the one you need. Let me know if you encounter any problem. 


    
    package com.example.farhan.testtouchimageview;

    import android.content.Context;
    import android.support.v4.view.PagerAdapter;
    import android.support.v4.view.ViewPager;
    import android.support.v7.app.AppCompatActivity;
    import android.os.Bundle;
    import android.view.View;
    import android.view.ViewGroup;
    import android.widget.LinearLayout;

    import com.squareup.picasso.Picasso;

    import java.util.ArrayList;

    public class TestViewPager extends AppCompatActivity {

    boolean pageChanged = false;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test_view_pager);
        final ExtendedViewPager mViewPager = (ExtendedViewPager) findViewById(R.id.view_pager);
        ArrayList<String> URLs = new ArrayList<>();
        URLs.add("http://zanvent.com/test2/images/buscover/desh-travels-cover.png");
        URLs.add("http://zanvent.com/test2/images/buscover/relax-cover.jpg");
        assert mViewPager != null;
        mViewPager.setAdapter(new TouchImageAdapter(URLs, this));
        mViewPager.setPageMargin(30);

        mViewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                
            }

            @Override
            public void onPageSelected(int position) {
                pageChanged = true;
            }

            @Override
            public void onPageScrollStateChanged(int state) {
                if(state == ViewPager.SCROLL_STATE_IDLE && pageChanged){
                    for(int i = 0; i < mViewPager.getChildCount(); i++){
                        TouchImageView touchImageView = (TouchImageView) mViewPager.getChildAt(i);
                        if(touchImageView.isZoomed()){
                            touchImageView.resetZoom();
                        }
                    }
                    pageChanged = false;
                }

            }
        });
    }

        static class TouchImageAdapter extends PagerAdapter {

            private ArrayList<String> URLs;
            private Context context;

            public TouchImageAdapter(ArrayList<String> URLs, Context mContext) {
                this.URLs = URLs;
                context = mContext;
            }


            @Override
            public int getCount() {
                return URLs.size();
            }

            @Override
            public View instantiateItem(ViewGroup container, int position) {
                TouchImageView img = new TouchImageView(container.getContext());
                Picasso.with(context).load(URLs.get(position)).into(img);
                container.addView(img, LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
                return img;
            }
        
            @Override
            public void destroyItem(ViewGroup container, int position, Object object) {
                container.removeView((View) object);
            }

            @Override
            public boolean isViewFromObject(View view, Object object) {
                return view == object;
            }
        
        }
    }

**Comment by CoolMind** [comment]
@Neetras Thanks! A resetZoom() now works as expected.

**Comment by fadlurahmanf** [comment]
same problem here
