### ISSUE TITLE
TouchImageView in RecyclerView (Question)

### ISSUE THREAD

**Issue by BjoernPluester** [MikeOrtiz/TouchImageView#172]
I was trying to use this class to display multiple fullscreen images in a RecyclerView. This works fine, but the zooming is very awkward to use, I think there is a conflict with the scrolling of the RecyclerView. How can I make the TouchImageView touch events override the RecyclerView events?

**Comment by hannesa2** [comment]
The zooming has some improvement in last version. 
If it still exists there, we all are happy about any pull request solving any issue
