### ISSUE TITLE
Glide and insert into TouchImageView (with solution)

### ISSUE THREAD

**Issue by ImageViewGlide** [MikeOrtiz/TouchImageView#178]
I have been trying to use glide in my app, but it won't load any images:

    Glide.with(this).load(urinormal).into(exampleTouchImageView);

before that I was using this code which worked fine:

    exampleTouchImageView.setImageURI(urinormal);

Using `Glide` with a normal `ImageView` also works, but I need zooming.

I also tried putting it into a bitmap, but I couldn't do that on the main thread and `AsyncTasks` get buggy here as I have a `ViewPager`.

**Comment by IvanGarza07** [comment]
hello i had the same problem and i solved with this code

SimpleTarget target = new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap bitmap, GlideAnimation<? super Bitmap> glideAnimation) {
                imageViewGallery.setImageBitmap(bitmap);
            }
        };

you can use the simpletarget glide's for set the bitmap to touchimageview

**Comment by bholota** [comment]
It's because needs View size and it's not available in TouchImageView implementation before bitmap is set.

**Comment by miroslavign** [comment]
Any idea how to do it in glide 4 ?

**Comment by miroslavign** [comment]
Here is the solution (although marked as deprecated, but I don't care at the moment)
```
                ViewTarget viewTarget = new ViewTarget<TouchImageView, Drawable>(imageView) {
                        @Override
                        public void onResourceReady(@NonNull Drawable drawable, Transition<? super Drawable> transition) {
                            this.view.setImageDrawable(drawable);
                            if (drawable instanceof GifDrawable) {
                                GifDrawable gd = (GifDrawable) drawable;
                                gd.start();
                            }
                        }
                    };
                GlideApp
                        .with(imageView.getContext())
                        .load(image)
                        .into(viewTarget);
```

**Comment by kishanverma26** [comment]
> SimpleTarget

this one is deprecated

**Comment by edysolisaritec** [comment]
Here is the solution!

```
GlideApp.with(this)
        .load(url)
        .thumbnail(0.1f)
        .into(new CustomTarget<Drawable>() {
            @Override
            public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
               touchImageView.setImageDrawable(resource);
            }

            @Override
            public void onLoadCleared(@Nullable Drawable placeholder) {

            }
        });
```

**Comment by hannesa2** [comment]
I guess we need a sample for this

**Comment by hannesa2** [comment]
Here is a Glide example https://github.com/MikeOrtiz/TouchImageView/pull/277
