### ISSUE TITLE
When i use setImageBitmap , sometimes image can't showing and bitmap is not empty.

### ISSUE THREAD

**Issue by handy0529** [MikeOrtiz/TouchImageView#180]
When i use setImageBitmap , sometimes image can't showing and bitmap is not empty. 
Can you help me ? 
Thank you!

**Comment by deepakcipl** [comment]
Same problem I was facing. I have solved the problem by setting zoom 0.99f as follows:-
imageView.setZoom(0.99f);

where imageView is reference of TouchImageView. I was facing this problem in ImageLoader, so I just put the above line in onLoadingComplete method. You can also put the same line before loading the image url  to glide or ImageLoader but better to put it after loading complete. Enjoy :)

**Comment by m7mdra** [comment]
its really weird bug, i resolved it by set the zoom to `0.0f` but then the image was too small however setting it to `0.99f` did fortunately solve the problem.
