### ISSUE TITLE
Zoom is not working for a drawn circle

### ISSUE THREAD

**Issue by pgokul8537** [MikeOrtiz/TouchImageView#181]
TouchImageView class in onDraw method i have implemented following code to draw circle

            dotPaint.setColor(ContextCompat.getColor(getContext(), R.color.map_site_dot));              
            Point point = site.getPoint();                
            canvas.drawCircle((float) point.getX(), (float) point.getY(),
                    ViewUtils.dpToPx(DOT_DEFAULT_RADIUS), dotPaint);
but circle is not displaying.

If i have used dispatchDraw override method to draw circle it draw over the image. then zoom not getting applied for drawned circle, only its working for the below image. Could you please help me in this.

**Comment by jeunetoujour** [comment]
Any updates or hints on this one. This is basically a question on how to use the zoom ability with canvas drawings. Most canvas drawings appear to be a layer on top of the bitmap while the library focuses on the bitmap.

**Comment by evanbattaglia** [comment]
In terms of positioning (not zoom), I was able to draw a circle in a specific image point by translating that to the view point using the center position and zoom level. However this would be a lot easier if `transformCoordTouchToBitmap` and `transformCoordBitmapToTouch` were not private. Any chance of making those protected? Instead I am having to do something like:

```kotlin
    override fun onDraw(canvas: Canvas?) {
        scrollPosition?.let { centerBitmapPercentage ->
            val centerBitmapX = centerBitmapPercentage.x * drawable.intrinsicWidth
            val centerBitmapY = centerBitmapPercentage.y * drawable.intrinsicHeight

            val pinViewX = (width / 2F) + (pinBitmapX - centerBitmapX) * currentZoom
            val pinViewY = (height / 2F) + (pinBitmapY - centerBitmapY) * currentZoom
            ....
        }
    }
```

Also I haven't yet figured out how to check if the image is loaded / ready to draw, that may be require accessing another private variable / method.

**Comment by hannesa2** [comment]
Now `transformCoordTouchToBitmap` and `transformCoordBitmapToTouch` are protected https://github.com/MikeOrtiz/TouchImageView/pull/233 please use new version `2.3.2`

**Comment by evanbattaglia** [comment]
Awesome thanks so much! If I see something else simple I need I will make a pull request :)
