### ISSUE TITLE
This repository is dead. Link to improved fork is included.

### ISSUE THREAD

**Issue by Ruberik** [MikeOrtiz/TouchImageView#186]
This repository hasn't been seriously updated since 2016. Many issues have already been fixed in hanessa2's version: https://github.com/hannesa2/TouchImageView

If you have issues with this repository (and even if you don't), consider using that version and seeing whether your problems have already been solved. If not, consider filing an issue or pull request there.

**Comment by hannesa2** [comment]
I'm a collaborator now and I will merge PRs immediate

**Comment by Ruberik** [comment]
Awesome!

**Comment by hannesa2** [comment]
Let's see how does it works, @MikeOrtiz has to add this repo to Travis to build each PR. This is a hard requirement and I can't do it
