### ISSUE TITLE
Using TouchImageView in RecyclerView

### ISSUE THREAD

**Issue by RageshAntony** [MikeOrtiz/TouchImageView#191]
I was trying to use this class to display multiple fullscreen images in a RecyclerView attached with PageSnapHelper

This works fine, but the zooming is very awkward to use .If I try to pinch zoom , the image moving left and right but not zooming. Only double Tap works.

 I think there is a conflict with the swiping and scrolling of the RecyclerView attached with PageSnapHelper .

How can I make the TouchImageView touch events override the PageSnapHelper events when pinch zoomed byt swiping also works when swiped?

To be simple , I want the same behavior of Chat Apps(Whatsapp and telegram) Image Slider which supports both swiping and pinch zooming  

Note , I searched the stackoverflow but there are only solutions for ViewPagers but no recyclerview

**Comment by hannesa2** [comment]
Please can you provide a sample ?

**Comment by mihudevcom** [comment]
Same issue here. Basically a simple screen with a RecyclerView and the only different thing is that I add this to it: 
`SnapHelper snapHelper = new PagerSnapHelper();
        snapHelper.attachToRecyclerView(recyclerView);`

And I'm experiencing the same issues as @RageshAntony mentioned.

**Comment by hannesa2** [comment]
@mihudevcom 
Thank you for your example, I add a running example https://github.com/MikeOrtiz/TouchImageView/pull/217 to demonstrate how to do so.
