### ISSUE TITLE
Option to disable zoom on double tap

### ISSUE THREAD

**Issue by ramden** [MikeOrtiz/TouchImageView#192]
Hi,
I saw the question multiple times but found no solution:

How to disable zooming on double tap? 

Currently I am forced to have this feature enabled. 

Would it be reasonable to have a feature to disable it programatically ? (like imageView.disableDoubleTapZoom())

I have a situation where I need to detect the double tap but I don't want it to zoom (only via pinch-zoom)

**Comment by hannesa2** [comment]
here you can use it
`implementation 'com.github.MikeOrtiz:TouchImageView:2.2.0' // Android X`

**Comment by hannesa2** [comment]
Btw I see the feature request to have a send-a-beer-to-the-maintainer button in the demo app

**Comment by ramden** [comment]
Gradle currently cannot resolve 2.2.0, only 2.1.1. 
Is 2.2.0 tagged?

**Comment by hannesa2** [comment]
Ahh sorry, I pushed the tag only to my fork
`implementation 'com.github.hannesa2:TouchImageView:2.2.0'`
now you can do this too
`implementation 'com.github.MikeOrtiz:TouchImageView:2.2.0'`

**Comment by ramden** [comment]
The implemented option disables double tap completely. 
As I mentioned in my question, just the zoom should be disabled on double tap, not double tap itself

> @Override
        public boolean onDoubleTap(MotionEvent e) {
            boolean consumed = false;
            if (isZoomEnabled()) { // <---- THIS CONDITION
                if (doubleTapListener != null) {
                    consumed = doubleTapListener.onDoubleTap(e);
                }
                if (state == State.NONE) { // SHOULD_BE_HERE -> if (state == State.NONE && isZoomEnabled()) 
                    float targetZoom = (normalizedScale == minScale) ? maxScale : minScale;
                    DoubleTapZoom doubleTap = new DoubleTapZoom(targetZoom, e.getX(), e.getY(), false);
                    compatPostOnAnimation(doubleTap);
                    consumed = true;
                }
            }
            return consumed;
        }

I think this way you would achieve it the best way and solve many issue requests that are similar to this

**Comment by hannesa2** [comment]
Feel free to make a PR, then it will fit exactly your needs
