### ISSUE TITLE
postTranslate Programatically ?

### ISSUE THREAD

**Issue by GauravCreed** [MikeOrtiz/TouchImageView#199]
How can i postTranslate() through coding on fixed point. I want to focus image on fixed (X,Y) after zoom,

1.  Zoom image 
2. after zoom image focus of imageview on some (X,Y) co-ordinate value,

i already use `imageview.setZoom(zoomvalue,X,Y)` not working.

**Comment by hannesa2** [comment]
Please tell us exactly what you mean. Two word does explain not much

**Comment by GauravCreed** [comment]
Here is my original image
![device-2019-04-16-142837](https://user-images.githubusercontent.com/13447384/56196297-325d3780-6054-11e9-91e8-8edae6b911f1.png)

and after zoom my image look like this.
![device-2019-04-16-142901](https://user-images.githubusercontent.com/13447384/56196327-3ee19000-6054-11e9-8791-f8714bf3404a.png)



i want to zoom image on fixed gray part of image.

**Comment by hannesa2** [comment]
To the explain a task is often a minimum requirement. We've I understand right you want to zoom to grey 'e' on tap ?

I recommend to have look at OpenCV, detect features and based on them zoom programmatically to it

**Comment by GauravCreed** [comment]
Hi @hannesa2 

let me explain you, i have default co-ordinate without zoom (100,250), okay then i zoom image on perform some action and then after zoom image i want to (X,Y)(100,250) point in center of screen with zoom.

Thanks.

**Comment by hannesa2** [comment]
Of course there is a solution, because everything has solution !

As you know exactly what should happen and I see this lib not as a major point to fulfil your task (as far as I understood), I guess you should at least start with it by your own.

If you develop a feature, which should be shared with the world, we love to approve your pull request
