### ISSUE TITLE
Weird load with Glide & sharedElement transition

### ISSUE THREAD

**Issue by DanteAndroid** [MikeOrtiz/TouchImageView#210]
![Screenshot_1567866490](https://user-images.githubusercontent.com/10005563/64476216-da6bcc80-d1be-11e9-87e6-b7d506ccc1d0.png)
The picture is loaded only a corner (and zoomed state). Tried `app:zoom_enabled="false"` still not working. And it turns normal after one click (after that it's still unzoomable)
This situation happens a lot. And it blinks from time to time when loading the picture.

I have a demo [here](https://github.com/DanteAndroid/BestPracticeWithGlideSharedTransition). Please check out.

**Comment by hannesa2** [comment]
When you close the solution of your not-building-repo https://github.com/DanteAndroid/BestPracticeWithGlideSharedTransition/pull/2#issuecomment-688665225 I can't help here anymore
