### ISSUE TITLE
Release 1.4.0 empty on Jitpack

### ISSUE THREAD

**Issue by FDuhen** [MikeOrtiz/TouchImageView#222]
Hello,

When checking on Jitpack, the folder 1.4.0 is only containing the build.log
https://jitpack.io/com/github/MikeOrtiz/TouchImageView/1.4.0

We can't download the library anymore

Thank you

**Comment by hannesa2** [comment]
What's about to upgrade to a more recent one ?

**Comment by hannesa2** [comment]
No clue what's going on, only 2.3.0 shows content https://jitpack.io/com/github/MikeOrtiz/TouchImageView/2.3.0/

<img width="531" alt="image" src="https://user-images.githubusercontent.com/3314607/69529091-e1111100-0f6f-11ea-86b4-d22adf86672d.png">

**Comment by FDuhen** [comment]
Sadly I'm working on projects which aren't AndroidX ready, that's why we're stuck with the version 1.4.0
I retrieved the *.aar file on my computer and uploaded it on a local maven to temporarily fix my problem, but someone else may be stuck someday

**Comment by hannesa2** [comment]
Now I tried this 1.4.1 build and **NOW** it builds
<img width="553" alt="image" src="https://user-images.githubusercontent.com/3314607/69539559-09efd100-0f85-11ea-8571-f46141cf514b.png">

Please give `1.4.0` a try again, or simply use `1.4.1`
