### ISSUE TITLE
Wish: Set zoomin value for doubletab

### ISSUE THREAD

**Issue by TomPeak** [MikeOrtiz/TouchImageView#225]
What would be nice is to have a setting, for how much to zoom in on doubletab. Too be able, to get bigger after tabzoom.

Thx, for your great work so far!

**Comment by hannesa2** [comment]
Yes, but I'm not sure which value you want to adjust.
Point me to it, or better: Make a pull request

**Comment by TomPeak** [comment]
Line 1010 not - minZoom : maxZoom  for me would work minZoom : tapZoom 
I don't dare to touch your code. Thanks for replay!
