### ISSUE TITLE
Error: Cannot fit requested classes in a single dex file

### ISSUE THREAD

**Issue by Abu-Abdullah** [MikeOrtiz/TouchImageView#230]
facing issue with only v 2.3.1
```
Cannot fit requested classes in a single dex file
```

version 2.3.0 is OK

**Comment by hannesa2** [comment]
When you look on [diff](https://github.com/MikeOrtiz/TouchImageView/compare/2.3.0..2.3.1) you see not that much changes in directory `touchview`. Module `app` is not important.

So we need a deeper look into it
### 2.3.0
`git checkout origin/MethodCount-2.3.0 && ./gradlew clean :touchview:assembleDebug`

<img width="390" alt="image" src="https://user-images.githubusercontent.com/3314607/70881968-91ea5900-1fce-11ea-8354-33e05b369caf.png">

### 2.3.1
`git checkout origin/MethodCount-2.3.1 && ./gradlew clean :touchview:assembleDebug`

<img width="385" alt="image" src="https://user-images.githubusercontent.com/3314607/70882027-bf370700-1fce-11ea-809a-4a114b39ba9c.png">

### summary
Maybe `TouchimageView` triggers your dex issue with 22(!) more methods , but it's in permille range.
You were before already on the edge and you should maybe investigate on your side, which lib causes the most methods. Btw, often Rx consumes a lot, and Joda is a nightmare

**Comment by Abu-Abdullah** [comment]
I'm not sure, when i enable minifyEnabled with proguardFiles it is running smooth. i have looked at diff and it seems you have added many additional dependencies e.g. recyclerview , viewpager2 that i have in my project as well. im not sure if this is causing the issue.

the strange is that even with these additions, it should not exceed the 65K limit. the version after enabling  minifyEnabled and proguardFiles has only 30k

im not sure here but certainly the 2.3.1 is conflicting somehow with my project and causes this issue. i do not want to enable multiDex if these is no need for that

**Comment by hannesa2** [comment]
> you have added many additional dependencies e.g. recyclerview , viewpager2

In the demo app, not in the lib !

Use the plugin like in my branch https://github.com/MikeOrtiz/TouchImageView/tree/MethodCount-2.3.1 on your project and look at the report, then you see what's wrong

> when i enable minifyEnabled with proguardFiles it is running smooth

You know what to do
