### ISSUE TITLE
Add a Frame to ImageView

### ISSUE THREAD

**Issue by RowerPulido** [MikeOrtiz/TouchImageView#236]
Im trying to add a custom frame to an image into the TouchImageView but if I added to the Background it doesn't allow and lose the capability to adapt it to the LayoutParams.

Do you know if exists a way to solve that?

**Comment by hannesa2** [comment]
> Do you know if exists a way to solve that?

No, I don't know how does your custom frame looks like.

As a first step, to demonstrate your issue, you could make a PR where you change/add the demo app. Then it's much easier to help.
