### ISSUE TITLE
Preserver zoom and fill the screen

### ISSUE THREAD

**Issue by prysme01** [MikeOrtiz/TouchImageView#252]
Hello, 

First of all, I would like to thank @MikeOrtiz for this piece of code, this is great !

I am working on a comicbook reader, then I have two questions : 
1. I am wondering how can I deal with having TouchImageView fill my screen with an image while applying a zoom factor depending on the screen size and orientation (fit to width or fit to height in vertical mode)
2. While using a ViewPager (Extendend ViewPager) How can I preserve the zoom factor from one image to another ?

Thanks for your help.
e.

**Comment by hannesa2** [comment]
Did you already did something ? If yes, please be more specific.

There are several samples included and when they don't show you the path for your solution, you could make an additional sample with your (unsolved) problem as pull request. This way helps me as maintainer the most.
