### ISSUE TITLE
method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference

### ISSUE THREAD

**Issue by JusticeOfHeaven** [MikeOrtiz/TouchImageView#253]
![image](https://user-images.githubusercontent.com/23259769/77525264-b73b0d00-6ec3-11ea-9f36-7ebfb0214422.png)

Maybe we should use other way to get drawable's width to avoid crash

**Comment by JusticeOfHeaven** [comment]
version：1.4.0

**Comment by hannesa2** [comment]
Please use `2.3.3`, because this error finding in archeological version is a waste of time

**Comment by hannesa2** [comment]
If it appears in most recent version as well, please update ticket with new stacktrace and reopen ticket
