### ISSUE TITLE
Calling setImageDrawable resets image

### ISSUE THREAD

**Issue by jahirfiquitiva** [MikeOrtiz/TouchImageView#257]
So, I am loading an image with a url. First I load a thumbnail, then the full res image.

Once the thumbnail loads, I set the image using `setImageDrawable`. And the same for the full res image.

The problem is, if I zoom or move the thumbnail, before the full res image is set, the imageview does not keep its scroll position or its scale.

![Grabación de pantalla 2020-04-18 a la(s) 19 17 16](https://user-images.githubusercontent.com/10360816/79675361-f7339e00-81aa-11ea-993c-986ecf268082.gif)

**Comment by hannesa2** [comment]
I guess the issue is somewhere [here](https://github.com/MikeOrtiz/TouchImageView/blob/master/touchview/src/main/java/com/ortiz/touchview/TouchImageView.java#L196-L202)

    @Override
    public void setImageDrawable(Drawable drawable) {
        imageRenderedAtLeastOnce = false;
        super.setImageDrawable(drawable);
        savePreviousImageValues();
        fitImageToView();
    }

I would look into `fitImageToView()` and we accept pull requests. Maybe we should overload this method without

        savePreviousImageValues();
        fitImageToView();

When I should do something, prepare an example in sample app as pull request and I can have a deeper look

**Comment by hannesa2** [comment]
I made a new version https://github.com/MikeOrtiz/TouchImageView/releases/tag/3.0.0 which probably solve it. But you didn't provided an example, so I didn't tested it.

Now you can do 
`setImageDrawable(drawable, false)`

Please tell me, if it works properly

**Comment by jahirfiquitiva** [comment]
Thanks

Mind adding it for `setImageResource`, `setImageBitmap` and `setImageURI` as well?

Also, I'd like to suggest some code improvements:

```kotlin
	fun setImageDrawable(drawable: Drawable?, fitImage: Boolean) {
        imageRenderedAtLeastOnce = false
        super.setImageDrawable(drawable)
        if (fitImage) {
            savePreviousImageValues()
            fitImageToView()
        }
    }

    override fun setImageDrawable(drawable: Drawable?) {
        setImageDrawable(drawable, true)
    }
```

**Comment by jahirfiquitiva** [comment]
I also gave it a try but it is worse now... See how the image is bigger and bigger after the higher res picture is set.

Here's where I'm calling `setImageDrawable` in my project.
https://github.com/jahirfiquitiva/Frames/blob/bef3062780a02654646d06b91a37d3ba6b74be98/library/src/main/kotlin/dev/jahir/frames/ui/animations/SaturatingImageViewTarget.kt#L75

![Grabación de pantalla 2020-04-19 a la(s) 14 09 03](https://user-images.githubusercontent.com/10360816/79697484-b7bb8f00-8248-11ea-994b-7361c3e6bd0c.gif)

**Comment by hannesa2** [comment]
> I also gave it a try but it is worse now... See how the image is bigger and bigger after the higher res picture is set.

Ok, I will revert it.
Btw, it's a public code and pull requests are welcome

**Comment by jahirfiquitiva** [comment]
@hannesa2 I know it is, but I really don't know what to do to help. Appreciate the effort tho... Thanks in advance

**Comment by hannesa2** [comment]
If you really don't know how to help, this maybe helps https://github.com/firstcontributions/first-contributions

.. then start to debug, improve, commit, ....
