### ISSUE TITLE
Zooming and dragging behaving differently after changing from android 4.4 device to android 9.0 tablet.

### ISSUE THREAD

**Issue by AGulshi** [MikeOrtiz/TouchImageView#263]
Here is my original stackoverflow question: https://stackoverflow.com/questions/61368561/android-9-0-what-effect-does-changing-to-new-android-version-have-on-the-behavio

I used this custom imageview to draw points on a canvas and in the android 4.4 device, when I changed the position of a point in real time, the zooming and dragging would apply to the changing point as well and it was good. In the android 9.0 device, that same code doesn't work the same (no changes made to the code)  as the view is zoomed and dragged. 

`public void mapPoint (double x, double y) {

        if (lastPoint != null) {
            movableCan.drawCircle(lastPoint.x, lastPoint.y, 5, mPaint);
        }

        PointF mapped = mapper.mapPoint(x, y, getCurrentZoom());
        PointF corrected = transformCoordTouchToBitmap(mapped.x, mapped.y, true);

        movableCan.drawCircle(corrected.x, corrected.y, 5, green);
        this.setImageBitmap(movable);
        lastPoint.set(corrected.x, corrected.y);
    }`

On the android 4.4 device, I didn't need to use the transformCoordTouchToBitmap function but for the android 9.0 device I do. I don't know how to solve this issue since it happened because of a device change.

**Comment by hannesa2** [comment]
I answered it on stackoverflow. Please click on your link
