### ISSUE TITLE
android.view.InflateException

### ISSUE THREAD

**Issue by saimr** [MikeOrtiz/TouchImageView#27]
Hi I am using universal image downloader open source library to display images in grid view. When you click on the image on the grid, it shows in bigger format. 

I am trying to get zoom functionality work by using TouchImageView library. 
 I have added package com.example.touch in my src which has one file i.e. ImageViewTouch.java
Here is the xml file code:

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"

```
android:layout_width="fill_parent"
android:layout_height="fill_parent"
android:padding="1dip" >

<com.example.touch.TouchImageView
    android:id="@+id/image"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:adjustViewBounds="true"/>

<ProgressBar
    android:id="@+id/loading"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:visibility="gone" />
```

</FrameLayout>

Now in the code, I use the TouchViewImage as follows:

@Override
        public Object instantiateItem(ViewGroup view, int position) {
            View imageLayout = inflater.inflate(R.layout.activity_item_pager_image, view, false);
            //img =  findViewById(R.id.snoop);

```
         TouchImageView vOne  = (TouchImageView) imageLayout.findViewById(R.id.image);
```

final ProgressBar spinner = (ProgressBar) imageLayout.findViewById(R.id.loading);
imageLoader.displayImage(Constants.imageList.get(position), vOne, options, new SimpleImageLoadingListener() {
                @Override
                public void onLoadingStarted(String imageUri, View view) {
                    spinner.setVisibility(View.VISIBLE);
                }

```
            @Override
            public void onLoadingFailed(String imageUri, View view, FailReason failReason) {
                String message = null;
                switch (failReason) { }
                Toast.makeText(ImagePagerActivity.this, message, Toast.LENGTH_SHORT).show();

                spinner.setVisibility(View.GONE);
            }

            @Override
            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                spinner.setVisibility(View.GONE);
            //  bitmapImage = loadedImage;
                ;
            }
        });

        ((ViewPager) view).addView(imageLayout, 0);
        imagePosition=position;
```

//          Toast toast = Toast.makeText(getBaseContext(), "Position is " + position,
//                   Toast.LENGTH_LONG);
//                   toast.show();
            return imageLayout;
        }

```
    @Override
    public boolean isViewFromObject(View view, Object object) {
        return view.equals(object);
    }

    @Override
    public void restoreState(Parcelable state, ClassLoader loader) {
    }
    @Override
    public void setPrimaryItem(ViewGroup container, int position, Object object) {
        mCurrentView = (View)object;
    }

    @Override
    public Parcelable saveState() {
        return null;
    }

    @Override
    public void startUpdate(View container) {
    }
}
```

}

The problem is that when i click on the thumb in grid, i get the following error:

04-04 19:57:11.827: E/AndroidRuntime(12445): FATAL EXCEPTION: main
04-04 19:57:11.827: E/AndroidRuntime(12445): android.view.InflateException: Binary XML file line #8: Error inflating class com.example.touch.TouchImageView
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.LayoutInflater.createView(LayoutInflater.java:596)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at com.nostra13.example.universalimageloader.ImagePagerActivity$ImagePagerAdapter.instantiateItem(ImagePagerActivity.java:480)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:692)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.support.v4.view.ViewPager.populate(ViewPager.java:821)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.support.v4.view.ViewPager.populate(ViewPager.java:772)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1234)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.View.measure(View.java:15473)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5056)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.View.measure(View.java:15473)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.View.measure(View.java:15473)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5056)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2361)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.View.measure(View.java:15473)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1974)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1217)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1390)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1112)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4472)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.Choreographer.doFrame(Choreographer.java:525)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.os.Handler.handleCallback(Handler.java:615)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.os.Handler.dispatchMessage(Handler.java:92)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.os.Looper.loop(Looper.java:137)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.app.ActivityThread.main(ActivityThread.java:4898)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at java.lang.reflect.Method.invokeNative(Native Method)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at java.lang.reflect.Method.invoke(Method.java:511)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at dalvik.system.NativeStart.main(Native Method)
04-04 19:57:11.827: E/AndroidRuntime(12445): Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
04-04 19:57:11.827: E/AndroidRuntime(12445):    at java.lang.Class.getConstructorOrMethod(Class.java:460)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at java.lang.Class.getConstructor(Class.java:431)
04-04 19:57:11.827: E/AndroidRuntime(12445):    at android.view.LayoutInflater.createView(LayoutInflater.java:561)
04-04 19:57:11.827: E/AndroidRuntime(12445):    ... 38 more

Please help me remove this

**Comment by my1347** [comment]
same problem
