### ISSUE TITLE
What is this white space when sent match_parent?

### ISSUE THREAD

**Issue by bd901029** [MikeOrtiz/TouchImageView#273]
![Screenshot_1595356537](https://user-images.githubusercontent.com/46511221/88093206-429f8300-cbc4-11ea-94bc-980e3cf3c8f0.png)

**Comment by hoangtu23** [comment]
Can you share layout file?

**Comment by bd901029** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	xmlns:app="http://schemas.android.com/apk/res-auto">

	<ProgressBar
		android:id="@+id/progressBar"
		style="?android:attr/progressBarStyleSmall"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		app:layout_constraintStart_toStartOf="parent"
		app:layout_constraintEnd_toEndOf="parent"
		app:layout_constraintTop_toTopOf="parent"
		app:layout_constraintBottom_toBottomOf="parent"/>

	<com.ortiz.touchview.TouchImageView
		android:id="@+id/imageView"
		android:layout_width="0dp"
		android:layout_height="0dp"
		android:background="@color/black"
		android:contentDescription="@null"
		app:layout_constraintStart_toStartOf="parent"
		app:layout_constraintEnd_toEndOf="parent"
		app:layout_constraintTop_toTopOf="parent"
		app:layout_constraintBottom_toBottomOf="parent"/>

</androidx.constraintlayout.widget.ConstraintLayout>
