### ISSUE TITLE
Failed to resolve: com.github.MikeOrtiz:TouchImageView:3.0.3

### ISSUE THREAD

**Issue by IbrahimOmar91** [MikeOrtiz/TouchImageView#278]
Hello,
I am having this error when I try to sync my project
Failed to resolve: com.github.MikeOrtiz:TouchImageView:3.0.3

I tried all versions available in the link https://jitpack.io/#MikeOrtiz/TouchImageView/3.0.3

Any advice ?

**Comment by hannesa2** [comment]
Because the artifacts are build, 
![image](https://user-images.githubusercontent.com/3314607/90725312-45bf8900-e2c0-11ea-9a0d-29485639c5f3.png)

the problem is located on your machine

Maybe try a  `./gradlew clean --refresh-dependencies`

**Comment by IbrahimOmar91** [comment]
I tried "gradlew clean --refresh-dependencies" as you suggested but still have the same issue.

**Comment by hannesa2** [comment]
You did both steps ?

<img width="697" alt="image" src="https://user-images.githubusercontent.com/3314607/90852690-73680900-e378-11ea-9229-02147219e50a.png">


I can only guess what's wrong without code. 
Without code and without exact error, I stop here
