### ISSUE TITLE
TouchImageView exceeds its parent bounds while zooming in

### ISSUE THREAD

**Issue by vammex** [MikeOrtiz/TouchImageView#302]
let's say i have 2 frame layouts one above another and each one takes a half of my screen. The TouchImageView is a child of the top layout 
![a1](https://user-images.githubusercontent.com/19187347/103353412-c77fb880-4ae3-11eb-80f4-126549566383.PNG)
while zooming in, the view expands and just fills all the available space
![a2](https://user-images.githubusercontent.com/19187347/103353422-cea6c680-4ae3-11eb-9ac4-8163b9e5f40e.PNG)
instead of that i'd expect to zoom the view inside the bounds of its parent - the frame layout  - just like
![a3](https://user-images.githubusercontent.com/19187347/103353438-d4041100-4ae3-11eb-9816-7c67387010ce.png)

is it possible?
may be, the solution is in onMeasure() function code where the width and the height are set

**Comment by hannesa2** [comment]
> may be, the solution is in onMeasure() function code where the width and the height are set

Yes, this could be and sounds very promising ! 

And to be honest, don't expect too much help without a running example which demonstrate the issue. If you really want to provide it, please make a pull request with an additional demo activity here 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/3314607/103357935-aa7fc100-4ab4-11eb-8523-2f4860419b9d.png">

**Comment by vammex** [comment]
> And to be honest, don't expect too much help without a running example which demonstrate the issue.

do you mean i have to upload a project that demonstrates the process as it is explained by the pics i uploaded? What is a purpose of the pics if so? They don't show the issue clearly?
and, the project must be uploaded via pull request? not here?

**Comment by vammex** [comment]
@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        Drawable drawable = getDrawable();
        if (drawable == null || drawable.getIntrinsicWidth() == 0 || drawable.getIntrinsicHeight() == 0) {
            setMeasuredDimension(0, 0);
            return;
        }

       //  int heightSize  -> here it probably should be referenced to a real parent view and its dimensions
      // i.e. parent height is 1000dp, heightSize should accordingly be equal to an <equivalent of 1000dp in Integer>

        heightMeasureSpecSaved = heightMeasureSpec;
        int drawableWidth = drawable.getIntrinsicWidth();
        int drawableHeight = drawable.getIntrinsicHeight();
        int widthSize = MeasureSpec.getSize(widthMeasureSpec);
        int widthMode = MeasureSpec.getMode(widthMeasureSpec);
        int heightSize = MeasureSpec.getSize(heightMeasureSpec);
        int heightMode = MeasureSpec.getMode(heightMeasureSpec);
        viewWidth = setViewSize(widthMode, widthSize, drawableWidth);
        viewHeight = setViewSize(heightMode, heightSize, drawableHeight);

        //
        // Set view dimensions
        //
        setMeasuredDimension(viewWidth, viewHeight);

        //
        // Fit content within view
        //
        fitImageToView();
    }
