### ISSUE TITLE
Cant free move image

### ISSUE THREAD

**Issue by miladesign** [MikeOrtiz/TouchImageView#303]
Hi. thanks for this library. if i zoom out image then image is always in center. cant move it to corners for example. can you fix this?
if i change this:
```
MotionEvent.ACTION_MOVE -> if (state == State.DRAG) {
 val deltaX = curr.x - last.x
 val deltaY = curr.y - last.y
 val fixTransX = getFixDragTrans(deltaX, viewWidth.toFloat(), imageWidth)
 val fixTransY = getFixDragTrans(deltaY, viewHeight.toFloat(), imageHeight)
 touchMatrix!!.postTranslate(fixTransX, fixTransY)
 fixTrans()
 last[curr.x] = curr.y
}
```
to this:
```
MotionEvent.ACTION_MOVE -> if (state == State.DRAG) {
 val deltaX = curr.x - last.x
 val deltaY = curr.y - last.y
 touchMatrix!!.postTranslate(deltaX, deltaY )
 last[curr.x] = curr.y
}
```

its work but when i save image nothing change.

**Comment by hannesa2** [comment]
You want to have it, maybe others don't. That's why it needs an attribute to choose.

Independent of this, if there is a pull request, I'll approve it immediate

**Comment by miladesign** [comment]
thanks. i used this code and its work good now:
```
MotionEvent.ACTION_MOVE -> if (state == State.DRAG) {
 val deltaX = curr.x - last.x
 val deltaY = curr.y - last.y
 touchMatrix!!.postTranslate(deltaX, deltaY )
 fixTrans()
 last[curr.x] = curr.y
}
```

**Comment by hannesa2** [comment]
I made a pull request out of your suggestion https://github.com/MikeOrtiz/TouchImageView/pull/304

To be honest, I don't get the point, what's now better with your suggestion. This is the master branch

https://user-images.githubusercontent.com/3314607/103453335-3b36e680-4cd9-11eb-85ad-97568912f405.mp4

Please can you demonstrate your improvement ?

**Comment by miladesign** [comment]
Hi. i used this library inside PhotoEditor library. so before i made any changes i resize image but it was always in center. after i made that change now i can resize image and move it then save it using PhotoEditor library.

**Comment by nrodrigues55681** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/14937791/172011084-d6b90bd3-5e3f-49f3-92a4-07cbb432df95.png">

How can i free move my image? Is it possible using the TouchImageView? Like you can see I have an overlay and i would like to crop by the overlay.

I have configure the TouchImageView 
scaleType = ImageView.ScaleType.CENTER_CROP
maxZoom = 5f
minZoom = 1f
