### ISSUE TITLE
Incompatibility between Viewpager2, TouchImageView and BottomSheetBehavior

### ISSUE THREAD

**Issue by JorisBodin** [MikeOrtiz/TouchImageView#315]
I use viewpage2 and for zoom, move the photo and slider, I followed your example here: https://github.com/MikeOrtiz/TouchImageView/blob/master/app/src/main/java/info/touchimage/demo/custom/AdapterImages.kt
But it is incompatible with BottomSheetBehavior

The exemple is here: https://github.com/JorisBodin/TouchImageView/tree/bug-viewpager2

https://user-images.githubusercontent.com/2796439/105740726-c3f01d80-5f39-11eb-9dc2-40f62b574866.mp4

Is there a solution for this case? Thank you in advance :)

**Comment by hannesa2** [comment]
Simple solutions are always the best.

```
class ViewPager2ExampleActivity : AppCompatActivity() {

    public override fun onCreate(savedInstanceState: Bundle?) {
        ...
        binding.bottomSheetFileInfos.setOnTouchListener { v, event ->
            true
        }
    }
}
```

https://user-images.githubusercontent.com/3314607/106241436-56c4dc80-6206-11eb-9fb9-1be15fcd496d.mov

Please consider to buy me a coffee

**Comment by JorisBodin** [comment]
@hannesa2 Big thank you :)
It's perfect et very simple. I was looking for a more complicated solution ...
