### ISSUE TITLE
This 'setZoom' method is weird

### ISSUE THREAD

**Issue by SimFG** [MikeOrtiz/TouchImageView#326]
when I call setZoom(1.1f, 0, 0), the ImageView has an offset in the x direction and an offset in the Y direction. 
```
floatMatrix!![Matrix.MTRANS_X] = (viewWidth - matchViewWidth) / 2 - focusX * (scale - 1) * matchViewWidth
floatMatrix!![Matrix.MTRANS_Y] = (viewHeight - matchViewHeight) / 2 - focusY * (scale - 1) * matchViewHeight
```
I think it might be more reasonable.

**Comment by hannesa2** [comment]
Please can you demonstrate it in `ChangeSizeExampleActivity` in a fork or pull request ?
Best with a screenshot

**Comment by SimFG** [comment]
I have pulled a request, and demonstrated it in the branch SetZoomOptCheck

**Comment by hannesa2** [comment]
Solved with https://github.com/MikeOrtiz/TouchImageView/releases/tag/3.0.4
