### ISSUE TITLE
How to set view heigh? setMaxHeight is ignored 

### ISSUE THREAD

**Issue by AlfaBravoX** [MikeOrtiz/TouchImageView#330]
Hi,

2nd line is ignored. Any idea, is that for purpose of TouchImageView implementation or it is a bug?

TouchImageView _iv;
_iv= getView().findViewById( R.id.iv_wc_latest );
_iv.setMaxHeight( 100 ); <--- line ignored

<com.ortiz.touchview.TouchImageView
                android:id="@+id/id1"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="fitXY" />

**Comment by hannesa2** [comment]
It a method from `ImageView` and out of context of this repository

**Comment by AlfaBravoX** [comment]
yes it is working in ImageView but why it is not in TouchImageView? are you saying it is not implemented?

**Comment by hannesa2** [comment]
Did you found an implementation?
The code is open source

**Comment by hannesa2** [comment]
To make one thing clear: I see myself only as approver of pull requests, to prevent this repositoy from death.
Changes, fixes and improvements are warmly welcome !
Next to this, I modernize it and keep it up to date.

What I don't do: solving general programming question, "or my code is not working", where I don't know what you did.

The only way is to ask **specific** questions, with **running code** !
I'm not interested to construct someones problem locally to replay his problem

**Comment by AlfaBravoX** [comment]
Fair enough and thanks for giving clear expectations. yes, right I could have check myself if setMaxHeight is implemented or not. However I'd appreciate if my question can be turned to improvement recommendation. This widget is awesome and definitely would please more coders if scaletype works a bit more efficient. For example see my #325 where i was trying to explain, that to display bitmap 1.3 aspect ratio the way that it fill whole parent width and scales height accordingly is practically impossible. Either image is stretched (fit_xy) or it does not fill whole TouchImageView area (matrix or centerInside or fitcenter) And if it fits then additional blank space is consumed on top and bottom of view. If i work in kotlin, then perhaps i could provide pull request but i just deal with Java.
