### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by emartynov** [MikeOrtiz/TouchImageView#332]
Appreciate your hard work! Could you also provide release notes? Grasping changes from master commits is quite tedious.

**Comment by hannesa2** [comment]
But commit history is the only point of truth !
At least the breaking change it there 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/3314607/110783627-fc895380-8268-11eb-9257-3b52fbc0e0ea.png">

.. if it's too less ? I love to see contributions !

**Comment by hannesa2** [comment]
Or maybe you need a better git tool. I at least don't like changelogs (for smaller repos) it hides often information

<img width="454" alt="image" src="https://user-images.githubusercontent.com/3314607/110784724-4fafd600-826a-11eb-9d18-007ccb12173a.png">

**Comment by hannesa2** [comment]
or use `git log --oneline 3.0.3..3.0.4`

**Comment by emartynov** [comment]
The last release is already providing some details. Apologies, I just didn't pick up that line as the only changelog and the rest releases are misleading.

I don't have checked out git repo, so I can not use any fancy git commands or programs.

I used https://github.com/marketplace/actions/release-changelog-builder with the previous project. That requires some discipline in the naming PRs but brings flowless release noting.

**Comment by emartynov** [comment]
I already own some contributions. Let me put this also on my todo list.
