### ISSUE TITLE
Scroll position does not match the arguments that I am sending to setZoom

### ISSUE THREAD

**Issue by MaryChek** [MikeOrtiz/TouchImageView#344]
Good afternoon, maybe I don't understand something.
The situation is this: We have a picture, when opening the application, a certain place with a certain zoom must be approached. I know the coordinate of the center of the object that should be approximated when opening and in the center of the screen.
With version 3.0.3, everything works as it should and scrollPosition (x, y) are the same as what I passed to setZoom, but in 3.0.5 there is a slight shift in the view (a little down and to the right)

**Comment by hannesa2** [comment]
I guess it was #329 from @SimFG 
Maybe he can clarify your question. 

If you think you found an error or you can improve it, then I'm happy to approve your pull request

**Comment by MaryChek** [comment]
yes, I saw this proposal, so I decided to check the version before the edits were made, and it turned out that it worked the way I thought it should be. What do you suggest to me to do? Discuss my problem with @SimFG?

**Comment by ajmirB** [comment]
Hello,

Just to let you know that I actually have the same regression than @MaryChek, 

And if i rollback the PR #329, it works like a charm.

**Comment by hannesa2** [comment]
Hmm, currently I've no smart idea how to make both uses cases work.
But to use an old version also not the way to go. I'm open minded for any nice solution
