### ISSUE TITLE
401 from public repository

### ISSUE THREAD

**Issue by dorado89** [MikeOrtiz/TouchImageView#347]
I am trying to use the library by following the instructions from jitpack.io page:
`	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
`
and
`		dependencies {
	        implementation 'com.github.MikeOrtiz:TouchImageView:3.0.6'
	}
`
but this is the response:
`Could not GET 'https://jitpack.io/com/github/MikeOrtiz/touchview/3.0.6/touchview-3.0.6.pom'. Received status code 401 from server: Unauthorized`
I also tried with versions 3.0.5 , 3.0.4 and 3.0.3

**Comment by hannesa2** [comment]
It works on CI https://github.com/hannesa2/LiveEdgeDetection/pull/170/files

**Comment by dorado89** [comment]
> 
> 
> It works on CI https://github.com/hannesa2/LiveEdgeDetection/pull/170/files

are you using some sort of credentials in your maven repository to download the dependency? Because it is asking credentials even if I am using browsers. This is the response if I don't give login and password: `Repo not found or no token provided`

**Comment by dorado89** [comment]
> 
> 
> > It works on CI https://github.com/hannesa2/LiveEdgeDetection/pull/170/files
> 
> are you using some sort of credentials in your maven repository to download the dependency? Because it is asking credentials even if I am using browsers. This is the response if I don't give login and password: `Repo not found or no token provided`

Sorry, my mistake. It was case sensitive the dependency
