### ISSUE TITLE
this library not working with glide?

### ISSUE THREAD

**Issue by H-Khoujani** [MikeOrtiz/TouchImageView#369]
i using glide in my project but when glide try to load image into TouchImageView that is happen fail and show blank dark screen

**Comment by hannesa2** [comment]
There is a sample https://github.com/MikeOrtiz/TouchImageView/blob/master/app/src/main/java/info/touchimage/demo/GlideExampleActivity.kt

a test https://github.com/MikeOrtiz/TouchImageView/blob/d0b5ac04fac76a6068658bc406e11cb534d16f6d/app/src/androidTest/java/info/touchimage/demo/MainSmokeTest.kt#L107 

and a screenshot during each pull request 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/3314607/122670355-fb4db800-d1c1-11eb-85e6-2296aa4dd494.png">

**Comment by hannesa2** [comment]
Ooops, I see the glide test is much too fast !

<img width="587" alt="image" src="https://user-images.githubusercontent.com/3314607/122670469-87f87600-d1c2-11eb-9c28-3e7707d56495.png">

I've to investigate ...

**Comment by hannesa2** [comment]
Ok, now the test with glide works now

![image](https://user-images.githubusercontent.com/3314607/122676219-69ec3f00-d1dd-11eb-936c-62451f8a6714.png)

For you question: Yes, it works with glide

**Comment by hannesa2** [comment]
If you find an error, please reopen this issue
