### ISSUE TITLE
Zoomed Image inside PagerAdapter

### ISSUE THREAD

**Issue by uwaisalqadri** [MikeOrtiz/TouchImageView#383]
I'm working on some e-commerce app with UX similar to TikTok, scroll up and down to see the next product, and using this library for zoomable images so user can see detail of the image, but the problem is when the user wants to scroll the pager, the image scrollable (as I expected) holding the pager to scroll, is there is a way to make the image stay zoomable but disabling the scroll? (especially in my case is for horizontal)

demo:
https://drive.google.com/file/d/1EtOzrqAi3q4voKVhhYdRiCm3NFAqzUGh/view?usp=sharing

**Comment by hannesa2** [comment]
> when the user wants to scroll the pager, the image scrollable holding the pager to scroll

What ? I'm not 100% sure what you want.

Anyway, maybe this points you in the right direction https://github.com/MikeOrtiz/TouchImageView/pull/317/files#diff-aab9fc04af15e52d80b1fc7ee0665aa2f48f610bc02dd8504088dfd5a422bb81R22-R24
