### ISSUE TITLE
How to move view center after zoomed?

### ISSUE THREAD

**Issue by nguyenlinhnttu** [MikeOrtiz/TouchImageView#390]
Hello Mike
Thanks for your library.
Now i have a problem, after zoomed by  fun setZoom(scale: Float, focusX: Float, focusY: Float, scaleType: ScaleType?) 
I want to move image to center.
https://ibb.co/5K6qKkb
Please help me guide to move image to center screen.

Thank

**Comment by hannesa2** [comment]
Did you looked in the sample ? Maybe there is already one such use case

**Comment by nguyenlinhnttu** [comment]
i can't sync sample project many issue on android studio :(

**Comment by hannesa2** [comment]
> i can't sync sample project many issue on android studio :(

You need the most recent one

**Comment by nguyenlinhnttu** [comment]
Thanks for your reply. My issue not resolve , but i force focusY = 0.5f to make it center.
It not good solution haha.
