### ISSUE TITLE
Missing license metadata in published packages

### ISSUE THREAD

**Issue by andrew8er** [MikeOrtiz/TouchImageView#396]
The published packages do not contain license metadata: 

https://mvnrepository.com/artifact/com.github.MikeOrtiz/TouchImageView/3.1.0

This makes it hard to use this library in applications that take licensing serious and generate license reports automatically.

**Comment by hannesa2** [comment]
I don't publish it there. No clue who did this, sorry.
I only publish to https://jitpack.io/#MikeOrtiz/TouchImageView there I could help you probably

**Comment by andrew8er** [comment]
The package listed on mvnrepository.com is the same as on jitpack.io.

The pom file has no license metadata: https://jitpack.io/com/github/MikeOrtiz/TouchImageView/3.1.0/TouchImageView-3.1.0.pom

I would have guessed, jitpack picks up the license from github's license field.

**Comment by hannesa2** [comment]
This is repository which needs collaboration. You can change anything with a pull request

**Comment by hannesa2** [comment]
Or this ? https://github.com/jitpack/jitpack.io/issues/1744#issue-255892333

> Many repositories contain a kind of LICENSE file. Maybe named with an extension like LICENSE.txt. This data could be analyses and written to the POM file automatically.

**Comment by andrew8er** [comment]
I will prepare a PR later, however, this should already work:

> JitPack uses GitHub API to detect the license and adds it to the pom.
If pom already has a license then it keeps it.

(from https://github.com/jitpack/jitpack.io/issues/1744#issuecomment-327766786)

This answer is from 2017, so it's not exactly a new feature…
