### ISSUE TITLE
Issue with scrolling for TouchImageView inside AppBarLayout / CollapsableToolbar

### ISSUE THREAD

**Issue by ShankarKakumani** [MikeOrtiz/TouchImageView#400]
Scenario:: I have an Activity with TouchImageView(top 60% of the screen) + Grid of GalleryImages ( bottom 40% of screen )

Functionality:: I have to Collapse/Expand the ImageView based on scroll direction. To achieve this I had to place the TouchImageView inside AppBarLayout / CollapsableToolBar

Issue:: When I try to zoom/pinch/scroll the TouchImageView, The AppBarLayout is getting scrolled. Which you can observe in the below Video

expected behavior:: While Interacting with TouchImageView, The AppBar should not be triggered.

The functionality which I am trying to achieve is the same as InstagramGallery.  

Video Link: https://drive.google.com/file/d/1B-C4eWHQD7AAYoqiJlFc7Wbc43C0SXoP/view?usp=sharing

you can observe that I am trying to scroll the image, but the AppBar scroll is performing.

**Comment by hannesa2** [comment]
https://github.com/MikeOrtiz/TouchImageView/issues/314#issuecomment-767017933

**Comment by ShankarKakumani** [comment]
I have found the solution

   setScollable(yourAppBarLayout, false)
   
   
    fun setScrollable(appBarLayout: AppBarLayout, scrollable: Boolean) {
        val layoutParams = appBarLayout.layoutParams as CoordinatorLayout.LayoutParams
        val behavior = (layoutParams.behavior as? AppBarLayout.Behavior) ?: AppBarLayout.Behavior()
        behavior.setDragCallback(object : AppBarLayout.Behavior.DragCallback() {
            override fun canDrag(appBarLayout: AppBarLayout): Boolean = scrollable
        })
        layoutParams.behavior = behavior
    }

**Comment by hannesa2** [comment]
Thank you for sharing your solution. ❤️
You are very welcome, to add a demo activity with this
