### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by deive** [MikeOrtiz/TouchImageView#430]
Hi, I have been getting a few Firebase crash reports of the following:
Fatal Exception: java.lang.IllegalArgumentException
Parameter specified as non-null is null: method com.ortiz.touchview.TouchImageView$e.onFling, parameter e1
com.ortiz.touchview.TouchImageView$GestureListener.onFling (TouchImageView.java:2)
android.view.GestureDetector.onTouchEvent (GestureDetector.java:812)
com.ortiz.touchview.TouchImageView$PrivateOnTouchListener.onTouch (TouchImageView.java:5)
android.view.View.dispatchTouchEvent (View.java:15195)

**Comment by hannesa2** [comment]
There was something in the past, which version do you use ?
I guess it was this 324a9228d25564cc97c6a825b7b13acfc0f463be

**Comment by deive** [comment]
I was using 3.0.1, sorry I missed that update. Updating to 3.1.1 now - thanks very much!
