### ISSUE TITLE
Version 2.3.3 not available anymore on JitPack

### ISSUE THREAD

**Issue by MiriamCordes** [MikeOrtiz/TouchImageView#437]
Hi :) 

we are using version 2.3.3 of TouchImageView but it seems not to be available on JitPack anymore. Could you have a look into it please? Thank you!

[JitPack Log](https://jitpack.io/com/github/MikeOrtiz/TouchImageView/2.3.3/build.log)

**Comment by MiriamCordes** [comment]
@hannesa2 sure that would be the other option if the issue can't be fixed soonish.

**Comment by hannesa2** [comment]
> @hannesa2 sure that would be the other option if the issue can't be fixed soonish.

It could only solved by a new release. That's why it's better to use a more recent anyways
