### ISSUE TITLE
I don't know how this app will work 

### ISSUE THREAD

**Issue by nburno** [MikeOrtiz/TouchImageView#447]
I wish  somethings works with me when I download App from Github from the first-time

For this app in build.grade, when inspecting the code

doFirst {
        new File(reportsDirectory).mkdirs()
    }
Can't resolve the Symbol File and hundreds of other errors.

**Comment by hannesa2** [comment]
No clue, it seems to be located to your local environment.
Just now, it builds on my mac locally
![image](https://user-images.githubusercontent.com/3314607/167769795-79d92731-8057-4c28-bfaf-ad3696803132.png)

and CI works properly on an Ubuntu and a mac system https://github.com/MikeOrtiz/TouchImageView/actions/workflows/Android-CI.yml

**Comment by hannesa2** [comment]
@nburno any update, or can I close issue ?
