### ISSUE TITLE
Free move

### ISSUE THREAD

**Issue by nrodrigues55681** [MikeOrtiz/TouchImageView#451]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/14937791/172011084-d6b90bd3-5e3f-49f3-92a4-07cbb432df95.png">

How can i free move my image? Is it possible using the TouchImageView? Like you can see I have an overlay and i would like to crop by the overlay.

I have configure the TouchImageView 
scaleType = ImageView.ScaleType.CENTER_CROP
maxZoom = 5f
minZoom = 1f

_Originally posted by @nrodrigues55681 in https://github.com/MikeOrtiz/TouchImageView/issues/303#issuecomment-1146631830_

**Comment by hannesa2** [comment]
Please test the example https://github.com/MikeOrtiz/TouchImageView/issues/303#issuecomment-753445499 if it fits your need.
In the meantime I close this issue assuming it will fulfill.
