### ISSUE TITLE
Incorrect zoom coordinates when calling setZoom()/setZoomAnimated()

### ISSUE THREAD

**Issue by bartek-wesolowski** [MikeOrtiz/TouchImageView#507]
I used an older version of `TouchImageView` in my map app. I have hardcoded point coordinates. I call `setZoomAnimated()` when someone searches for a particular point. When I updated to the newest version of `TouchImageView` then `setZoomAnimated()`/`setZoom()` started zooming on a different place even though the focus coordinates didn't change. On version 3.0.3 everything still works correctly. On 3.0.4 the focus coordinates are different.

__Steps to reproduce__
Use `TouchImageView` version 3.0.3 to show an image. Pan the image using `setZoom(2f, 0.7f, 0.7f)`. Take a screenshot.
Do the same for version 3.0.4. The screenshots will be different even though the focus coordinates are the same.

**Comment by hannesa2** [comment]
It looks like that it's related to #329

To be honest, it's a community project and I'm happy to merge any pull request

**Comment by bartek-wesolowski** [comment]
[This change](https://github.com/MikeOrtiz/TouchImageView/commit/bc7b5069f6287b8797765ce4d56fc6dac947c175) might have caused the problem.

**Comment by hannesa2** [comment]
[This change](https://github.com/MikeOrtiz/TouchImageView/commit/bc7b5069f6287b8797765ce4d56fc6dac947c175)  and #329 is the same  😁

But how to proceed ? I've no clue. @SimFG do you have an idea ?

**Comment by bartek-wesolowski** [comment]
You can use an image like the one below to test it. When I call `setZoom(3f, 0.75f, 0.75f)` I'd expect the focus to be on C7, and right now it's not there. Before the change it was working fine.

![test_grid](https://user-images.githubusercontent.com/3972790/213658328-ba94cacb-5064-4ef3-b052-8818ea4ff9de.png)

**Comment by bartek-wesolowski** [comment]
![TouchImageView comparison](https://user-images.githubusercontent.com/3972790/213659923-d181aaa0-4cad-42a5-a246-cda39e294e9e.png)

**Comment by hannesa2** [comment]
PR #509 doesn't fix the issue, but it helps hopefully later to find a solution with a test for zoom behavior.
At the bottom of the [job](https://github.com/MikeOrtiz/TouchImageView/actions/runs/3978850013) you'll find `Touch-Screenshots` and here you'll find 

![image](https://user-images.githubusercontent.com/3314607/213907554-76e1c304-770a-476d-a5f6-3e51cee83148.png)

This is the current situation. And at least it's a basground

![image](https://user-images.githubusercontent.com/3314607/213907519-b748c165-e5aa-4cd4-8d83-d54ff8aa6a79.png)

**Comment by bartek-wesolowski** [comment]
I think that the changes made in https://github.com/MikeOrtiz/TouchImageView/pull/329 should be reverted because the formula is incorrect. Isn't the situation described in https://github.com/MikeOrtiz/TouchImageView/pull/329#issuecomment-791245674 a feature and not a bug? If we focus on point 0,0, don't we expect the image to be moved down like that? If not, shouldn't we adjust `getFixTrans()` instead of `setZoom()`? I started working on it a bit, but I'm going on vacation tomorrow and won't have access to my computer for a week.

**Comment by bartek-wesolowski** [comment]
BTW, using [Paparazzi](https://github.com/cashapp/paparazzi) for screenshot tests would be nice.

**Comment by hannesa2** [comment]
> I started working on it a bit, but I'm going on vacation tomorrow and won't have access to my computer for a week.

I would love to see some outcome in the future !

**Comment by hannesa2** [comment]
closed with https://github.com/MikeOrtiz/TouchImageView/pull/514
