### ISSUE TITLE
Support publishing to n MavenCentral

### ISSUE THREAD

**Issue by Goooler** [MikeOrtiz/TouchImageView#569]
We would probably migrate to publishing on MavenCentral, cause some versions missed from Jitpack, like `1.3.5`

```sh
wget https://jitpack.io/com/github/MikeOrtiz/TouchImageView/3.5/TouchImageView-3.5.aar
--2023-12-02 11:16:57--  https://jitpack.io/com/github/MikeOrtiz/TouchImageView/3.5/TouchImageView-3.5.aar
Resolving jitpack.io (jitpack.io)... 198.18.3.213
Connecting to jitpack.io (jitpack.io)|198.18.3.213|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-02 11:16:57 ERROR 404: Not Found.
```

**Comment by hannesa2** [comment]
In https://jitpack.io/#MikeOrtiz/TouchImageView/3.5 the build was green. As I clicked on [logfile](https://jitpack.io/com/github/MikeOrtiz/TouchImageView/3.5/build.log), it showed me "not found".
But after close log file tab in browser, I see jitpack started build again .....

Not it's available 
<img width="904" alt="image" src="https://github.com/MikeOrtiz/TouchImageView/assets/3314607/cd55ad4b-d4c1-4af3-a46e-e0b3d181897e">

> We would probably migrate to publishing on MavenCentral,

I guess, it has no affect to this repository, when you migrate to MavenCentral. Am I right ?

**Comment by Goooler** [comment]
> As I clicked on [logfile](https://jitpack.io/com/github/MikeOrtiz/TouchImageView/3.5/build.log), it showed me "not found".
But after close log file tab in browser, I see jitpack started build again .....

It was published again, so it's available for now. There are some issues on Jitpack that haven't been fixed, one of them is about jar not found, but it's not happened on Maven Central. I suggest that we consider a migration.

**Comment by connyduck** [comment]
Yes please, Jitpack has so many problems

https://committing-crimes.com/articles/2024-09-09-jitpack/

**Comment by hannesa2** [comment]
Feel free to make a pull request to do so
