### ISSUE TITLE
Add instructions on how to integrate your library to a kotlin project

### ISSUE THREAD

**Issue by arilow** [MikeOrtiz/TouchImageView#619]
Hi! First, this library is exactly what I needed for a university project. So thank you very much for sharing it with the community.

Second, the instructions in the README tell how to integrate this library into a Groovy project. It took me a while to integrate it into my Kotlin project because I didn't know how to do it. It is kind of easy but it wouldn't hurt to add instructions for that too.

This is how I did it:

In `settings.gradle.kts` add:

```
dependencyResolutionManagement {
    ...
    repositories {
        ...
        maven {
            setUrl("https://jitpack.io")
        }
    }
}
```

In `build.gradle.kts` add:

```
dependencies {
    ...
    implementation("com.github.MikeOrtiz:TouchImageView:3.6")
 }
```

Again, thank you for sharing your effort.
Cheers

**Comment by hannesa2** [comment]
What's about this in the readme ? 
<img width="861" alt="image" src="https://github.com/user-attachments/assets/525c7ec0-53ca-448e-aec7-f35908055428">
