### ISSUE TITLE
Zooming and panning lags with large pictures

### ISSUE THREAD

**Issue by marjan89** [MikeOrtiz/TouchImageView#71]
@MikeOrtiz Hi,
I'm using TouchImageView and it's great in terms of simplicity and functionality, but the issue i'm having is lag while zooming and panning large images (8mp). Is there any workaround or fix? Thanks.

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
