### ISSUE TITLE
Does the library support rotation?

### ISSUE THREAD

**Issue by Hesamedin** [MikeOrtiz/TouchImageView#74]
Hi nice job man,

I integrated your library into my application, but I'm not able to rotate image by two fingers. I checked your code and didn't find relative method. Am I right?

Thanks

**Comment by DhavalSpaceO** [comment]
@zak84 @MikeOrtiz  @Hesamedin Which library we can use for rotate, move and scale functionality?

**Comment by agGitHub** [comment]
Anybody managed to add rotation with 2 fingers pinch ? Thanks !
