### ISSUE TITLE
Show full size image on startup

### ISSUE THREAD

**Issue by JackED42** [MikeOrtiz/TouchImageView#77]
Hello,

I am currently working on a program that will show up an imagedialog showing part of an image  with multitouch. I want the imagedialog to show the image fullsize initially and the ability to zoom out/drag to look at the other parts. I can't seem to change it to do this.Is this possible?

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
