### ISSUE TITLE
zoomed image gets invisible when nearby adview refreshes

### ISSUE THREAD

**Issue by felikz3** [MikeOrtiz/TouchImageView#80]
When using the TouchImageView and also having an AdView in the same Activity, then the following happens:
If the image has been zoomed, and the AdView initially loads its ad or refreshes it, then zoomed image will completely disapear. If the image has not been zoomed by the user, it will stay visible.

I've debugged this a bit and found out, that the gesture listener and all that stuff still works fine (even though there is no image being displayed).

**Comment by snigam-systango** [comment]
Ocurring for me too. I have tried Dev Branch & master Branch both

**Comment by iori57** [comment]
Occur in my case too. For my case I am toggling between fullscreen mode and hide/show navigation bar using the codes below:

To show fullscreen:
```
mMainView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);
```

To exit fullscreen:
```
mMainView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
```

Steps to reproduce:
1) Whether in fullscreen or not doesn't matter, zoom in to the right part of the image
2) Toggle to show fullscreen (if it is already in fullscreen, toggle it to exit fullscreen then toggle back again)
3) The image will not be zoomed in on the right part of the image anymore but on the left part.

I followed this blog on how to toggle between fullscreen mode: http://developer.sonymobile.com/knowledge-base/tutorials/android_tutorial/how-to-provide-your-app-users-with-maximum-screen-estate-tutorial/

**Comment by iori57** [comment]
I just solved my own issue.. 

### Explanation
For me orientation change don't have a problem because it will automatically trigger onConfigurationChanged, where savePreviousImageValues() is being called to save the current image state.

For my case of enter/exit full screen mode, onConfigurationChanged is not called at all, and we need to rely on another method instead - onWindowSystemUiVisibilityChanged.

### Solution
I added the code below inside TouchImageView.java, and it solves my problem.
```
@Override
    public void onWindowSystemUiVisibilityChanged(int visible) {
        super.onWindowSystemUiVisibilityChanged(visible);
        savePreviousImageValues();
    }
```

Hope this will help someone.

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
