### ISSUE TITLE
New TouchImageView with Universal Image Loader

### ISSUE THREAD

**Issue by christian160984** [MikeOrtiz/TouchImageView#81]
Until now I was using a old version of TouchImageView. I was using it with Universal Image Loader:

String[] images --> URLs Images

imageView = (TouchImageView) imageLayout.findViewById(R.id.imagenFullScreen);
imageLoader.displayImage(images[position], imageView, options, new SimpleImageLoadingListener()...

How I can implement your new code with my current code? Thanks

**Comment by yhung124** [comment]
I have the same problem, however, I find a solution in stackoverflow.
http://stackoverflow.com/questions/23288526/android-not-displayed-imageview-with-uil-and-touchimageview
Just try cwc's answer.

    In onLoadingStarted(), add view.setVisibility(View.GONE)
    In onLoadingComplete(), add view.setVisibility(View.VISIBLE)

Anything becomes perfect!

**Comment by hannesa2** [comment]
It's 4 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
