### ISSUE TITLE
Separate demo project

### ISSUE THREAD

**Issue by mufumbo** [MikeOrtiz/TouchImageView#82]
Hi Mike, 

What do you think about separating the demo project in another folder?

That way the library code is not related to the images and resources from the demo app. 

I find myself manually copying files to get new updates, rather than just merging the entire library project. 

I would go one step further and advise you to upload the demo app to the play store and link it in the README.me, so that way developers don't even need to compile that project... :)

What do you think?

thanks
rafa

**Comment by hannesa2** [comment]
last master has this separation
