### ISSUE TITLE
setZoom resets the scrolling

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MikeOrtiz/TouchImageView#84]
I'm trying to reset the zoom using an animation from the current state.

It works, but it also (from the beginning of the animation) resets where the user has went so far .

Here's the small snippet I'm using:
    ObjectAnimator.ofFloat(touchImageView, "zoom",touchImageView.getCurrentZoom(), 1.0f).setDuration(5000).start();

Is there any way to overcome this?

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
