### ISSUE TITLE
pointerIndex out of range on Zoom In/Out

### ISSUE THREAD

**Issue by Thamizhan** [MikeOrtiz/TouchImageView#87]
I receive the Following Crash when using TouchImageView and when user Zoom In/Out regularly, 

Log:
05-19 15:50:06.906: E/AndroidRuntime(18731): FATAL EXCEPTION: main
05-19 15:50:06.906: E/AndroidRuntime(18731): java.lang.IllegalArgumentException: pointerIndex out of range
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.MotionEvent.nativeGetAxisValue(Native Method)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.MotionEvent.getX(MotionEvent.java:2075)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1834)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1978)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1978)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1978)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1978)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1978)
05-19 15:50:06.906: E/AndroidRuntime(18731): at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2177)
05-19 15:50:06.906: E/AndroidRuntime(18731): at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1482)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.app.Dialog.dispatchTouchEvent(Dialog.java:745)
05-19 15:50:06.906: E/AndroidRuntime(18731): at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2125)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.View.dispatchPointerEvent(View.java:7577)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3376)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3308)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4421)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4399)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4505)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:178)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.os.MessageQueue.nativePollOnce(Native Method)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.os.MessageQueue.next(MessageQueue.java:125)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.os.Looper.loop(Looper.java:124)
05-19 15:50:06.906: E/AndroidRuntime(18731): at android.app.ActivityThread.main(ActivityThread.java:4949)
05-19 15:50:06.906: E/AndroidRuntime(18731): at java.lang.reflect.Method.invokeNative(Native Method)
05-19 15:50:06.906: E/AndroidRuntime(18731): at java.lang.reflect.Method.invoke(Method.java:511)
05-19 15:50:06.906: E/AndroidRuntime(18731): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043)
05-19 15:50:06.906: E/AndroidRuntime(18731): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
05-19 15:50:06.906: E/AndroidRuntime(18731): at dalvik.system.NativeStart.main(Native Method)

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
