### ISSUE TITLE
Not displayed ImageView with UIL and TouchImageView

### ISSUE THREAD

**Issue by kevinhwu** [MikeOrtiz/TouchImageView#89]
I've got a issue same as the following stackoverlow question:
http://stackoverflow.com/questions/23288526/android-not-displayed-imageview-with-uil-and-touchimageview

I'm trying to implement load images from a URL with Universal Image Loader and zoom with TouchImageView. But when trying to view the image, black screen is displayed. there are some cases:
1. It seems Camera photo can not shows, but other picture can shows.
2. If use ImageView instead of TouchImageView, image shows normally.
3. If remove progressBar, image show normally.

**Comment by drceogodpope** [comment]
That workaround only fixes the problem some times ...

**Comment by ImageViewGlide** [comment]
I have the same issue, but it isn't fixed by that solution. Using glide btw.

**Comment by hannesa2** [comment]
It's almost 5 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
