### ISSUE TITLE
Backing up the scaled image from TouchImageView to reused if the app is closed

### ISSUE THREAD

**Issue by johanngranados** [MikeOrtiz/TouchImageView#90]
Hello.

First all kudos for such a great widget!!!   I'm using it in an app where the people configure an avatar by taking a picture of themselves and then pinch the taken picture to adjust it in order to fit the avatar face transparent section.  That is working great.  The problem I'm facing is that I want the app to remember the adjusted (zoomed) image if the user closes the app and open it again.  I've tried getting the image from the TouchImageView instance by using the View.getDrawable()).getBitmap() but it returns the original image and not the scaled one.  So I tried to save that image as it comes from the View and then once the user restart the app setting it to the TouchImageView again and applying the setZoom method to the view (I previously got and saved the setZoom parameters values from the Image to the Shared Preferences).  However, the setZoom method is not working (the image is not getting zoomed in).  I then tried to applied the transformation matrix to the TouchImageView bitmap previously to save it but when I set that image to the TouchImageView instance again it gets zoomed out back). 

I'm just wondering if there is some recommendation you could give me to solve my issue. 

Thank you very much in advance!

**Comment by hannesa2** [comment]
It's almost 5 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
