### ISSUE TITLE
Coordinates transformation (to original image position)

### ISSUE THREAD

**Issue by jmcazaux** [MikeOrtiz/TouchImageView#92]
Hi Mike et all,
I am trying to use a subclass TouchImageView that displays an image plus some markers.
The location of the markers is known relatively to the original image.

So basically I need to transform the coordinates of a point in the original image to the panned and zoomed TouchImageView subclass.
I got it working with a normal image view, but I am having a hard time with the sub class.

I used getScrollPosition and getCurrentZoom, but I am missing the origin of the original image (where some space ahs been added to fit it in the image).

Any idea how I could achieve this ?
Any pointer is well come.
Thanks in advance,
JM

**Comment by vhakulinen** [comment]
Why transformCoordBitmapToTouch is private? It should be public so it can be used outside of the TouchImageView class.

**Comment by jinkim608** [comment]
I just made the two transform methods public to retrieve touch location relative to the image, instead of image view. Got the result I wanted.

    PointF point = touchImageView.transformCoordTouchToBitmap(event.getX(), event.getY(), true);

Thank you all for q&a. Awesome library!

**Comment by Harin-Kaklotar** [comment]
@jinkim608 thank you your method is really solve for my problem 
Thank you once again :1st_place_medal:  👍 
and thanks @MikeOrtiz for this beautiful lib :)
