### ISSUE TITLE
Inconsistent zoom and scroll status after onMeasure

### ISSUE THREAD

**Issue by Adrmedi** [MikeOrtiz/TouchImageView#94]
Steps to reproduce:
- Load an image and rotate the device (forcing a save instance state)
- Zoom and move the image
- Make another view visibility= View.GONE in order to force re-measurement
- The image zoom is reseted.

I think the base problem is this block at the fitImageToView method:

```
if (prevMatchViewWidth == 0 || prevMatchViewHeight == 0) {
        savePreviousImageValues();
    }
```

Currently I'm reseting the "prev" values at the end of the fitImageToView and seems to work correctly
Thanks for the library

**Comment by hannesa2** [comment]
With recent version, there are a lot if changes are done. Does it still exist ?
If yes, please reopen or better make a PR
