### ISSUE TITLE
Add note in sample that ViewPagers should use FragmentStatePagerAdapter

### ISSUE THREAD

**Issue by tjg1** [MikeOrtiz/TouchImageView#96]
The default PagerAdapter class isn't suitable for paging through large sets of ImageViews. It's not optimised to be memory efficient and developers will likely experience OutOfMemoryErrors fairly quickly when users scroll through a few high-res images, especially on low-end devices. For large sets of Views (fragments, actually) there is FragmentStatePagerAdapter in the v4 support library.

From the Android SDK [FragmentStatePagerAdapter](http://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter.html) docs:

> This version of the pager is more useful when there are a large number of pages, working more like a list view. When pages are not visible to the user, their entire fragment may be destroyed, only keeping the saved state of that fragment. This allows the pager to hold on to much less memory associated with each visited page as compared to FragmentPagerAdapter at the cost of potentially more overhead when switching between pages.

This is so poorly documented that I spent 10 months debugging OutOfMemoryErrors in my app, until I came across FragmentStatePagerAdapter completely by accident. Please correct your sample app and add a helpful note for other developers, so they don't have to suffer like I did.

**Comment by michaelhn** [comment]
Hi, do you have any update on this?

**Comment by hannesa2** [comment]
It's 5 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
