### ISSUE TITLE
linking each image to an item from a list view

### ISSUE THREAD

**Issue by MajdFreiha** [MikeOrtiz/TouchImageView#97]
i created an array composed from different images and a list.
i'm trying to put onClick listener for each item of the list to open a specified image from the array while keeping swiping from left to right and from right to left.
 example: if i click on item 4 of the list the image 4 from the array will open if i swipe from 
left to right : image 3 appear
right to left image 5 appear 
thank you :D

**Comment by hannesa2** [comment]
It's almost 5 years old, so it seems to be irrelevant. If it's still an issue, please reopen it
